"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { RadarLogo } from "./logo";

type Row = Record<string, string | number | null | undefined> & { id: string; organization_id?: string };
type Data = { employees: Row[]; inventory: Row[]; ppe: Row[]; documents: Row[] };
type Kind = "employees" | "inventory" | "ppe" | "documents";
type Tab = "overview" | Kind | "billing" | "admin";
type PaymentRequest = { id: string; organization_id: string; payment_reference?: string | null; status: string; created_at: string; organizations?: { name?: string; plan?: string; subscription_status?: string } | { name?: string; plan?: string; subscription_status?: string }[] | null };
type AdminOrganization = { id: string; name: string; plan: string; subscription_status: string; created_at: string };
type Props = { demo?: boolean; supabaseUrl?: string; supabaseKey?: string; userEmail?: string; organizationId?: string; organizationName?: string; role?: string; plan?: string; initialData?: Data; configurationError?: string; isPlatformAdmin?: boolean; kaspiPayUrl?: string; paymentRequests?: PaymentRequest[]; adminOrganizations?: AdminOrganization[] };

const nav: { id: Tab; label: string; icon: string }[] = [
  { id: "overview", label: "Оперативный центр", icon: "⌁" }, { id: "employees", label: "Работники", icon: "◯" },
  { id: "inventory", label: "Оборудование", icon: "◇" }, { id: "ppe", label: "СИЗ", icon: "⬡" },
  { id: "documents", label: "Документы", icon: "▤" }, { id: "billing", label: "Тариф и оплата", icon: "◫" },
];

const iso = (offset: number) => { const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10) };
const seed: Data = { employees: [
  { id: "e1", full_name: "Айдос Нурланов", department: "Техническая служба", position: "Электромонтёр", hire_date: iso(-430), medical_exam_expiry: iso(-3), briefing_expiry: iso(12), training_expiry: iso(74) },
  { id: "e2", full_name: "Алина Садыкова", department: "Лаборатория", position: "Инженер-химик", hire_date: iso(-210), medical_exam_expiry: iso(90), briefing_expiry: iso(4), training_expiry: iso(130) },
  { id: "e3", full_name: "Марат Ибраев", department: "Эксплуатация", position: "Техник", hire_date: iso(-95), medical_exam_expiry: iso(210), briefing_expiry: iso(170), training_expiry: iso(-9) },
], inventory: [
  { id: "i1", name: "Огнетушитель ОП-5 №118", category: "Пожарная безопасность", building: "Корпус A", location: "2 этаж", next_service_date: iso(7) },
  { id: "i2", name: "Пожарный кран ПК-14", category: "Пожарная безопасность", building: "Корпус B", location: "1 этаж", next_service_date: iso(-5) },
], ppe: [{ id: "p1", employee_name: "Айдос Нурланов", item_name: "Диэлектрические перчатки", quantity: 1, issued_at: iso(-200), replacement_date: iso(14) }], documents: [] };

function urgency(date?: string | number | null) { if (!date) return "red"; const days = Math.ceil((new Date(String(date)).getTime() - Date.now()) / 86400000); return days < 0 ? "red" : days <= 30 ? "yellow" : "green" }
function employeeStatus(e: Row) { const values = [e.medical_exam_expiry, e.briefing_expiry, e.training_expiry].map(urgency); return values.includes("red") ? "red" : values.includes("yellow") ? "yellow" : "green" }
function formatDate(value: unknown) { if (!value) return "—"; return new Intl.DateTimeFormat("ru-RU").format(new Date(`${String(value).slice(0,10)}T00:00:00`)) }
function Status({ value }: { value: string }) { const label = value === "red" ? "Недопуск" : value === "yellow" ? "Скоро срок" : "В норме"; return <span className={`status ${value}`}>{label}</span> }
function PaymentStatus({ value }: { value: string }) { const tone=value==='approved'?'green':value==='pending'?'yellow':'red'; const label=value==='approved'?'Подтверждён':value==='pending'?'На проверке':'Отклонён'; return <span className={`status ${tone}`}>{label}</span> }

export function Dashboard({ demo = false, supabaseUrl = "", supabaseKey = "", userEmail = "developer@hseradar.kz", organizationId, organizationName = "HSE Radar Demo", role = "owner", plan = "trial", initialData, configurationError, isPlatformAdmin = false, kaspiPayUrl = "", paymentRequests = [], adminOrganizations = [] }: Props) {
  const [tab, setTab] = useState<Tab>("overview"); const [data, setData] = useState<Data>(initialData || seed); const [menu, setMenu] = useState(false);
  const [editor, setEditor] = useState<{ kind: Kind; item?: Row } | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(configurationError || ""); const [paymentReference, setPaymentReference] = useState("");
  useEffect(() => { if (!demo) return; const saved = localStorage.getItem("hse-radar-next-demo"); if (saved) queueMicrotask(() => { try { setData(JSON.parse(saved)) } catch {} }); }, [demo]);
  useEffect(() => { if (demo) localStorage.setItem("hse-radar-next-demo", JSON.stringify(data)) }, [data, demo]);
  const hasUnlimitedAccess = isPlatformAdmin || plan !== "trial";
  const trialFull = (kind: Kind) => !hasUnlimitedAccess && data[kind].length >= 5;
  const openEditor = (kind: Kind, item?: Row) => {
    if (!item && trialFull(kind)) return setNotice("Лимит пробного тарифа исчерпан: максимум 5 записей в разделе. После подтверждения оплаты лимит снимается.");
    setEditor({ kind, item });
  };
  const risks = useMemo(() => data.employees.flatMap(e => [{ id:`${e.id}-m`, date:e.medical_exam_expiry, title:e.full_name, detail:"Медосмотр" }, { id:`${e.id}-b`, date:e.briefing_expiry, title:e.full_name, detail:"Инструктаж" }, { id:`${e.id}-t`, date:e.training_expiry, title:e.full_name, detail:"Обучение" }]).filter(x => urgency(x.date) !== "green").sort((a,b) => String(a.date).localeCompare(String(b.date))), [data.employees]);
  async function persist(kind: Kind, row: Row, update = false) {
    if (!update && trialFull(kind)) throw new Error("Лимит пробного тарифа: максимум 5 записей в разделе.");
    if (demo) { setData(d => ({ ...d, [kind]: update ? d[kind].map(x => x.id === row.id ? row : x) : [...d[kind], row] })); return }
    const supabase = createClient(supabaseUrl, supabaseKey); const table = kind === "ppe" ? "ppe_issues" : kind;
    const result = update ? await supabase.from(table).update(row).eq("id", row.id).select().single() : await supabase.from(table).insert({ ...row, organization_id: organizationId }).select().single();
    if (result.error) throw result.error; const saved = result.data as Row; setData(d => ({ ...d, [kind]: update ? d[kind].map(x => x.id === row.id ? saved : x) : [...d[kind], saved] }));
  }
  async function remove(kind: Kind, id: string) { if (!confirm("Удалить запись без возможности восстановления?")) return; if (!demo) { const table = kind === "ppe" ? "ppe_issues" : kind; const { error } = await createClient(supabaseUrl, supabaseKey).from(table).delete().eq("id", id); if (error) return setNotice(error.message) } setData(d => ({ ...d, [kind]: d[kind].filter(x => x.id !== id) })); }
  async function saveEditor(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!editor) return; setBusy(true); setNotice(""); try { const v = Object.fromEntries(new FormData(e.currentTarget)); const old: Row = editor.item || { id: "" }; const row: Row = { ...old, ...v, id: old.id || crypto.randomUUID() }; if (editor.kind === "ppe") row.quantity = Number(row.quantity); await persist(editor.kind, row, Boolean(editor.item)); setEditor(null) } catch (err) { setNotice(err instanceof Error ? err.message : "Не удалось сохранить") } finally { setBusy(false) } }
  async function upload(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (trialFull("documents")) { setNotice("Лимит пробного тарифа: максимум 5 документов."); e.target.value=""; return } if (demo) return persist("documents", { id:crypto.randomUUID(), name:file.name, category:"Загруженный документ", storage_path:"demo", created_at:new Date().toISOString() }); setBusy(true); try { const path = `${organizationId}/${crypto.randomUUID()}-${file.name}`; const supabase = createClient(supabaseUrl, supabaseKey); const uploaded = await supabase.storage.from("hse-documents").upload(path, file); if (uploaded.error) throw uploaded.error; await persist("documents", { id:crypto.randomUUID(), name:file.name, category:"Загруженный документ", storage_path:path, created_at:new Date().toISOString() }) } catch(err) { setNotice(err instanceof Error ? err.message : "Ошибка загрузки") } finally { setBusy(false); e.target.value="" } }
  async function logout() { if (demo) return location.reload(); await createClient(supabaseUrl, supabaseKey).auth.signOut(); location.reload() }
  async function submitPaymentRequest() { if (!organizationId) return; if (!paymentReference.trim()) return setNotice("Укажите комментарий или номер платежа из Kaspi Pay."); setBusy(true); const { error } = await createClient(supabaseUrl, supabaseKey).from("payment_requests").insert({ organization_id: organizationId, payment_reference: paymentReference.trim() }); setBusy(false); if (error) return setNotice(error.message); setNotice("Заявка отправлена. Полный доступ включится после проверки платежа руководителем платформы."); setPaymentReference(""); location.reload() }
  async function reviewPayment(id: string, action: "approve" | "reject") { setBusy(true); const { error } = await createClient(supabaseUrl, supabaseKey).rpc(action === "approve" ? "approve_payment_request" : "reject_payment_request", { request_id:id }); setBusy(false); if (error) return setNotice(error.message); location.reload() }
  const red = risks.filter(x => urgency(x.date) === "red").length, yellow = risks.filter(x => urgency(x.date) === "yellow").length;
  return <div className="app-shell">
    {demo && <div className="demo-bar">ДЕМО-РЕЖИМ · данные сохраняются только в этом браузере</div>}
    <aside className={menu ? "sidebar open" : "sidebar"}><RadarLogo /><p className="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</p><nav>{[...nav,...(isPlatformAdmin?[{id:"admin" as Tab,label:"Управление платформой",icon:"◆"}]:[])].map(n => <button key={n.id} className={tab === n.id ? "nav-item active" : "nav-item"} onClick={() => {setTab(n.id);setMenu(false)}}><span>{n.icon}</span>{n.label}</button>)}</nav><div className="account"><div className="avatar">{userEmail?.slice(0,2).toUpperCase()}</div><div><strong>{userEmail?.split("@")[0]}</strong><small>{isPlatformAdmin ? "Platform Admin" : role === "owner" ? "Администратор" : role}</small></div><button onClick={logout} title="Выйти">↗</button></div></aside>
    <main className="workspace"><header><button className="mobile-menu" onClick={() => setMenu(!menu)}>☰</button><div><span className="header-org">{organizationName}</span><small>{demo ? "Локальное пространство" : "Защищено Supabase RLS"}</small></div><div className="header-actions"><button className="icon-button" aria-label="Уведомления">♢<b>{red + yellow}</b></button><span className="plan">{plan.toUpperCase()}</span></div></header>
      {notice && <div className="toast"><span>{notice}</span><button onClick={() => setNotice("")}>×</button></div>}
      {tab === "overview" && <Overview data={data} risks={risks} red={red} yellow={yellow} add={() => openEditor("employees")} open={(t) => setTab(t)} />}
      {tab === "employees" && <ListPage title="Работники" eyebrow="РЕЕСТР И ДОПУСКИ" addLabel="Добавить сотрудника" onAdd={() => openEditor("employees")}><EmployeeTable rows={data.employees} edit={item => openEditor("employees",item)} remove={id => remove("employees",id)} /></ListPage>}
      {tab === "inventory" && <ListPage title="Оборудование" eyebrow="КОНТРОЛЬ СРОКОВ" addLabel="Добавить оборудование" onAdd={() => openEditor("inventory")}><InventoryTable rows={data.inventory} edit={item => openEditor("inventory",item)} remove={id => remove("inventory",id)} /></ListPage>}
      {tab === "ppe" && <ListPage title="Средства индивидуальной защиты" eyebrow="ВЫДАЧА И ЗАМЕНА" addLabel="Выдать СИЗ" onAdd={() => openEditor("ppe")}><PpeTable rows={data.ppe} edit={item => openEditor("ppe",item)} remove={id => remove("ppe",id)} /></ListPage>}
      {tab === "documents" && <ListPage title="Документы" eyebrow="ЕДИНОЕ ХРАНИЛИЩЕ" addLabel=""><label className="upload button primary">{busy ? "Загрузка…" : "+ Загрузить документ"}<input type="file" onChange={upload} disabled={busy} /></label><Documents rows={data.documents} remove={id => remove("documents",id)} /></ListPage>}
      {tab === "billing" && <Billing plan={plan} unlimited={hasUnlimitedAccess} isPlatformAdmin={isPlatformAdmin} data={data} kaspiPayUrl={kaspiPayUrl} paymentReference={paymentReference} setPaymentReference={setPaymentReference} submit={submitPaymentRequest} busy={busy} pending={paymentRequests.some(x=>x.organization_id===organizationId&&x.status==="pending")} />}
      {tab === "admin" && isPlatformAdmin && <AdminPanel organizations={adminOrganizations} requests={paymentRequests} busy={busy} review={reviewPayment} />}
    </main>{editor && <Editor kind={editor.kind} item={editor.item} busy={busy} close={() => setEditor(null)} save={saveEditor} employees={data.employees} />}
  </div>;
}

function Overview({data,risks,red,yellow,add,open}:{data:Data;risks:{id:string;date:string|number|null|undefined;title:string|number|null|undefined;detail:string}[];red:number;yellow:number;add:()=>void;open:(t:Tab)=>void}) { return <><section className="page-heading"><div><span className="eyebrow">ОПЕРАТИВНЫЙ ЦЕНТР</span><h1>Что требует внимания сегодня</h1><p>{new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"}).format(new Date())} · данные обновлены сейчас</p></div><button className="button dark" onClick={add}>＋ Добавить сотрудника</button></section><section className="priority"><div><span className="eyebrow light">ПРИОРИТЕТЫ</span><h2>{red+yellow} задач требуют решения</h2><p>Система собрала просрочки и ближайшие сроки в одну очередь.</p><button onClick={()=>open("employees")} className="button lime">Открыть очередь</button></div><div className="radar-visual"><i/><i/><i/><b/></div></section><div className="metrics"><Metric value={red} label="Критические просрочки" tone="red"/><Metric value={yellow} label="Срок в ближайшие 30 дней" tone="yellow"/><Metric value={data.employees.length} label="Работников в реестре"/><Metric value={data.inventory.length+data.ppe.length} label="Объектов под контролем"/></div><section className="panel"><div className="panel-title"><div><span className="eyebrow">ОЧЕРЕДЬ ДЕЙСТВИЙ</span><h3>Требуют внимания</h3></div><button className="button secondary" onClick={()=>open("employees")}>Все работники →</button></div>{risks.length ? risks.slice(0,6).map(r=><div className="risk-row" key={r.id}><Status value={urgency(r.date)}/><div><strong>{r.title}</strong><small>{r.detail}</small></div><time>{formatDate(r.date)}</time><span>→</span></div>) : <Empty text="Критичных задач нет"/>}</section></> }
function Metric({value,label,tone=""}:{value:number;label:string;tone?:string}) { return <div className={`metric ${tone}`}><b>{value}</b><span>{label}</span><i/></div> }
function ListPage({title,eyebrow,addLabel,onAdd,children}:{title:string;eyebrow:string;addLabel:string;onAdd?:()=>void;children:React.ReactNode}) { return <><section className="page-heading compact"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{addLabel && <button className="button dark" onClick={onAdd}>＋ {addLabel}</button>}</section>{children}</> }
const Actions=({item,edit,remove}:{item:Row;edit:(x:Row)=>void;remove:(id:string)=>void})=><div className="row-actions"><button onClick={()=>edit(item)}>Изменить</button><button className="danger-link" onClick={()=>remove(item.id)}>Удалить</button></div>;
function EmployeeTable({rows,edit,remove}:{rows:Row[];edit:(x:Row)=>void;remove:(id:string)=>void}) { return <section className="panel table-panel">{rows.length?<table><thead><tr><th>Статус</th><th>Ф.И.О.</th><th>Подразделение</th><th>Должность</th><th>Инструктаж</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><Status value={employeeStatus(x)}/></td><td><strong>{x.full_name}</strong></td><td>{x.department}</td><td>{x.position}</td><td>{formatDate(x.briefing_expiry)}</td><td><Actions item={x} edit={edit} remove={remove}/></td></tr>)}</tbody></table>:<Empty text="Работники ещё не добавлены"/>}</section> }
function InventoryTable({rows,edit,remove}:{rows:Row[];edit:(x:Row)=>void;remove:(id:string)=>void}) { return <section className="panel table-panel">{rows.length?<table><thead><tr><th>Статус</th><th>Наименование</th><th>Категория</th><th>Здание / место</th><th>Следующее обслуживание</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><Status value={urgency(x.next_service_date)}/></td><td><strong>{x.name}</strong></td><td>{x.category}</td><td>{x.building} · {x.location}</td><td>{formatDate(x.next_service_date)}</td><td><Actions item={x} edit={edit} remove={remove}/></td></tr>)}</tbody></table>:<Empty text="Оборудование ещё не добавлено"/>}</section> }
function PpeTable({rows,edit,remove}:{rows:Row[];edit:(x:Row)=>void;remove:(id:string)=>void}) { return <section className="panel table-panel">{rows.length?<table><thead><tr><th>Статус</th><th>Работник</th><th>СИЗ</th><th>Количество</th><th>Дата замены</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><Status value={urgency(x.replacement_date)}/></td><td><strong>{x.employee_name}</strong></td><td>{x.item_name}</td><td>{x.quantity}</td><td>{formatDate(x.replacement_date)}</td><td><Actions item={x} edit={edit} remove={remove}/></td></tr>)}</tbody></table>:<Empty text="Выдачи СИЗ ещё не зарегистрированы"/>}</section> }
function Documents({rows,remove}:{rows:Row[];remove:(id:string)=>void}) { return <section className="panel document-grid">{rows.length?rows.map(x=><article className="document" key={x.id}><span>PDF</span><div><strong>{x.name}</strong><small>{x.category} · {formatDate(x.created_at)}</small></div><button onClick={()=>remove(x.id)}>×</button></article>):<Empty text="Загрузите первый документ"/>}</section> }
function Empty({text}:{text:string}) { return <div className="empty"><div>⌁</div><strong>{text}</strong><span>Здесь появятся рабочие записи организации.</span></div> }
function Billing({plan,unlimited,isPlatformAdmin,data,kaspiPayUrl,paymentReference,setPaymentReference,submit,busy,pending}:{plan:string;unlimited:boolean;isPlatformAdmin:boolean;data:Data;kaspiPayUrl:string;paymentReference:string;setPaymentReference:(v:string)=>void;submit:()=>void;busy:boolean;pending:boolean}) { const usage=[['Работники',data.employees.length],['СИЗ',data.ppe.length],['Документы',data.documents.length],['Инвентарь',data.inventory.length]] as const; return <><section className="page-heading compact"><div><span className="eyebrow">ПОДПИСКА</span><h1>Тариф и оплата</h1></div></section><section className="billing-grid"><article className="plan-card"><span className="eyebrow">HSE RADAR PRO</span><h2>Вся система.<br/>Без ограничений.</h2><ul><li>Без лимитов на рабочие записи</li><li>Допуски, СИЗ и оборудование</li><li>Хранилище документов</li><li>Роли и защищённый доступ</li></ul>{unlimited?<div className="active-plan">✓ {isPlatformAdmin?'Полный доступ Platform Admin':'Полный доступ активен'}</div>:<>{kaspiPayUrl?<a className="button lime wide" href={kaspiPayUrl} target="_blank" rel="noreferrer">Оплатить через Kaspi Pay</a>:<div className="billing-warning">Ссылка Kaspi Pay ещё не добавлена разработчиком.</div>}<label className="payment-reference">Комментарий или номер платежа<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Например: HSE Radar · Компания" /></label><button className="button secondary wide" disabled={busy||pending} onClick={submit}>{pending?'Платёж проверяется':busy?'Отправка…':'Я оплатил — отправить на проверку'}</button></>}</article><article className="panel"><span className="eyebrow">ТЕКУЩИЙ СТАТУС</span><h3>{isPlatformAdmin?'Доступ администратора':plan === "pro" ? "Подписка активна" : "Пробный режим: до 5"}</h3><p className="muted">{unlimited?'Ограничения пробного режима не применяются к этому аккаунту.':'Лимит действует отдельно для каждого раздела и контролируется базой данных, а не только интерфейсом.'}</p><div className="usage-grid">{usage.map(([label,value])=><div key={label}><span>{label}</span><strong>{value} / {unlimited?'∞':5}</strong><i><b style={{width:unlimited?'100%':`${Math.min(value/5*100,100)}%`}}/></i></div>)}</div></article></section></> }

function AdminPanel({organizations,requests,busy,review}:{organizations:AdminOrganization[];requests:PaymentRequest[];busy:boolean;review:(id:string,action:'approve'|'reject')=>void}) { const orgName=(r:PaymentRequest)=>{const o=Array.isArray(r.organizations)?r.organizations[0]:r.organizations;return o?.name||r.organization_id}; return <><section className="page-heading compact"><div><span className="eyebrow">PLATFORM ADMIN</span><h1>Управление платформой</h1><p>Централизованная активация клиентов и контроль тарифов.</p></div></section><div className="admin-metrics"><Metric value={organizations.length} label="Организаций"/><Metric value={organizations.filter(x=>x.plan==='pro').length} label="Полный доступ"/><Metric value={requests.filter(x=>x.status==='pending').length} label="Платежей на проверке" tone="yellow"/></div><section className="panel table-panel"><div className="panel-title"><div><span className="eyebrow">KASPI PAY</span><h3>Заявки на активацию</h3></div></div>{requests.length?<table><thead><tr><th>Организация</th><th>Комментарий</th><th>Дата</th><th>Статус</th><th></th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{orgName(r)}</strong></td><td>{r.payment_reference||'—'}</td><td>{formatDate(r.created_at)}</td><td><PaymentStatus value={r.status}/></td><td>{r.status==='pending'&&<div className="row-actions"><button disabled={busy} onClick={()=>review(r.id,'approve')}>Подтвердить</button><button disabled={busy} className="danger-link" onClick={()=>review(r.id,'reject')}>Отклонить</button></div>}</td></tr>)}</tbody></table>:<Empty text="Заявок на оплату пока нет"/>}</section></> }

function Editor({kind,item,busy,close,save,employees}:{kind:Kind;item?:Row;busy:boolean;close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void;employees:Row[]}) { const titles={employees:"Сотрудник",inventory:"Оборудование",ppe:"Выдача СИЗ",documents:"Документ"}; return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{item?"РЕДАКТИРОВАНИЕ":"НОВАЯ ЗАПИСЬ"}</span><h2>{titles[kind]}</h2></div><button type="button" onClick={close}>×</button></div><div className="form-grid">{kind==="employees"&&<><Field name="full_name" label="Ф.И.О." value={item?.full_name} wide/><Field name="department" label="Подразделение" value={item?.department}/><Field name="position" label="Должность" value={item?.position}/><Field name="hire_date" label="Дата приёма" type="date" value={item?.hire_date}/><Field name="medical_exam_expiry" label="Медосмотр до" type="date" value={item?.medical_exam_expiry}/><Field name="briefing_expiry" label="Инструктаж до" type="date" value={item?.briefing_expiry}/><Field name="training_expiry" label="Обучение до" type="date" value={item?.training_expiry}/></>}{kind==="inventory"&&<><Field name="name" label="Наименование" value={item?.name} wide/><Field name="category" label="Категория" value={item?.category}/><Field name="building" label="Здание" value={item?.building}/><Field name="location" label="Место" value={item?.location}/><Field name="next_service_date" label="Следующее обслуживание" type="date" value={item?.next_service_date}/></>}{kind==="ppe"&&<><label className="wide">Работник<select name="employee_name" defaultValue={String(item?.employee_name||"")} required><option value="">Выберите</option>{employees.map(e=><option key={e.id}>{e.full_name}</option>)}</select></label><Field name="item_name" label="Наименование СИЗ" value={item?.item_name}/><Field name="quantity" label="Количество" type="number" value={item?.quantity||1}/><Field name="issued_at" label="Дата выдачи" type="date" value={item?.issued_at}/><Field name="replacement_date" label="Дата замены" type="date" value={item?.replacement_date}/></>}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Отмена</button><button className="button dark" disabled={busy}>{busy?"Сохранение…":"Сохранить"}</button></div></form></div> }
function Field({name,label,type="text",value,wide=false}:{name:string;label:string;type?:string;value:unknown;wide?:boolean}) { return <label className={wide?"wide":""}>{label}<input name={name} type={type} defaultValue={value==null?"":String(value).slice(0,type==="date"?10:undefined)} required /></label> }
