"use client";
import { createContext, useContext, useEffect, useState } from "react";
type Locale="ru"|"kk"|"en";
const Context=createContext<{locale:Locale;setLocale:(value:Locale)=>void}>({locale:"ru",setLocale:()=>{}});
const d:Record<string,{kk:string;en:string}>={
"Оперативный центр":{kk:"Жедел басқару орталығы",en:"Operations center"},"Работники":{kk:"Қызметкерлер",en:"Employees"},"Должности":{kk:"Лауазымдар",en:"Job profiles"},"Оборудование":{kk:"Жабдық",en:"Equipment"},"СИЗ":{kk:"ЖҚҚ",en:"PPE"},"Документы":{kk:"Құжаттар",en:"Documents"},"Задачи":{kk:"Тапсырмалар",en:"Tasks"},"Обучение":{kk:"Оқыту",en:"Learning"},"Команда":{kk:"Команда",en:"Team"},"Журнал действий":{kk:"Әрекеттер журналы",en:"Audit log"},"Тариф и оплата":{kk:"Тариф және төлем",en:"Plan and billing"},"Управление платформой":{kk:"Платформаны басқару",en:"Platform administration"},
"Войти":{kk:"Кіру",en:"Sign in"},"Зарегистрироваться":{kk:"Тіркелу",en:"Sign up"},"Рабочая почта":{kk:"Жұмыс поштасы",en:"Work email"},"Пароль":{kk:"Құпиясөз",en:"Password"},"Имя":{kk:"Аты",en:"Name"},"С возвращением":{kk:"Қош келдіңіз",en:"Welcome back"},"Создать пространство":{kk:"Жұмыс кеңістігін құру",en:"Create workspace"},"Нет аккаунта? Создать":{kk:"Аккаунт жоқ па? Құру",en:"No account? Create one"},"Уже есть аккаунт? Войти":{kk:"Аккаунт бар ма? Кіру",en:"Already registered? Sign in"},
"Что требует внимания сегодня":{kk:"Бүгін нені бақылау қажет",en:"What needs attention today"},"Открыть задачи":{kk:"Тапсырмаларды ашу",en:"Open tasks"},"Добавить сотрудника":{kk:"Қызметкер қосу",en:"Add employee"},"Критические просрочки":{kk:"Критикалық кешігулер",en:"Critical overdue items"},"Активных задач":{kk:"Белсенді тапсырмалар",en:"Active tasks"},"Работников в реестре":{kk:"Тізілімдегі қызметкерлер",en:"Employees in register"},
"Новая программа":{kk:"Жаңа бағдарлама",en:"New program"},"Формат":{kk:"Формат",en:"Format"},"Вид обучения":{kk:"Оқыту түрі",en:"Learning type"},"Название программы":{kk:"Бағдарлама атауы",en:"Program name"},"Инструктаж":{kk:"Нұсқама",en:"Briefing"},"Специальное обучение":{kk:"Арнайы оқыту",en:"Special training"},"Экзамен / проверка знаний":{kk:"Емтихан / білімді тексеру",en:"Exam / knowledge check"},"Вводный":{kk:"Кіріспе",en:"Induction"},"На рабочем месте":{kk:"Жұмыс орнында",en:"Workplace"},"Электробезопасность":{kk:"Электр қауіпсіздігі",en:"Electrical safety"},"Первая помощь":{kk:"Алғашқы көмек",en:"First aid"},"Назначить обучение":{kk:"Оқытуды тағайындау",en:"Assign learning"},"Назначить выбранным":{kk:"Таңдалғандарға тағайындау",en:"Assign selected"},"Срок прохождения":{kk:"Аяқтау мерзімі",en:"Completion deadline"},"Добавить вопрос":{kk:"Сұрақ қосу",en:"Add question"},"Завершить тест":{kk:"Тестті аяқтау",en:"Finish test"},
"Доступ и роли":{kk:"Қолжетімділік және рөлдер",en:"Access and roles"},"Роль":{kk:"Рөл",en:"Role"},"Пригласить":{kk:"Шақыру",en:"Invite"},"Владелец":{kk:"Иесі",en:"Owner"},"Руководитель":{kk:"Басшы",en:"Manager"},"Наблюдатель":{kk:"Бақылаушы",en:"Viewer"},"Удалить доступ":{kk:"Қолжетімділікті жою",en:"Remove access"},
"Новая должность":{kk:"Жаңа лауазым",en:"New job profile"},"Название":{kk:"Атауы",en:"Title"},"Обязательные поля":{kk:"Міндетті өрістер",en:"Required fields"},"Необходимое обучение":{kk:"Қажетті оқыту",en:"Required learning"},"Создать должность":{kk:"Лауазымды құру",en:"Create job profile"},
"Камера устройства":{kk:"Құрылғы камерасы",en:"Device camera"},"Запустить камеру":{kk:"Камераны іске қосу",en:"Start camera"},"Остановить":{kk:"Тоқтату",en:"Stop"},"Нарисовать опасную зону":{kk:"Қауіпті аймақты сызу",en:"Draw danger zone"},"Сохранить контур":{kk:"Контурды сақтау",en:"Save zone"},"Очистить":{kk:"Тазарту",en:"Clear"},"Создать событие":{kk:"Оқиға құру",en:"Create event"},"Создать задачу":{kk:"Тапсырма құру",en:"Create task"},
"Сохранить":{kk:"Сақтау",en:"Save"},"Отмена":{kk:"Бас тарту",en:"Cancel"},"Удалить":{kk:"Жою",en:"Delete"},"Выберите":{kk:"Таңдаңыз",en:"Select"},"Подразделение":{kk:"Бөлімше",en:"Department"},"Должность":{kk:"Лауазым",en:"Position"}
};
const source=new WeakMap<Node,string>();
function apply(root:Node,locale:Locale){const reverse=new Map<string,string>();for(const[k,v]of Object.entries(d)){reverse.set(k,k);reverse.set(v.kk,k);reverse.set(v.en,k)}const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){const raw=node.textContent||"",trim=raw.trim();if(!trim)continue;const key=source.get(node)||reverse.get(trim);if(!key||!d[key])continue;source.set(node,key);const target=locale==="ru"?key:d[key][locale];if(trim!==target)node.textContent=raw.replace(trim,target)}const elements=root===document.body?[...document.querySelectorAll("*")]:root instanceof Element?[root,...root.querySelectorAll("*")]:[];for(const el of elements)for(const attr of["placeholder","title","aria-label"]){const value=el.getAttribute(attr),key=value&&reverse.get(value);if(key&&d[key])el.setAttribute(attr,locale==="ru"?key:d[key][locale])}}
export function LanguageProvider({children}:{children:React.ReactNode}){const[locale,setValue]=useState<Locale>("ru");useEffect(()=>{const saved=localStorage.getItem("hse-language") as Locale|null;if(saved&&["ru","kk","en"].includes(saved))queueMicrotask(()=>setValue(saved))},[]);useEffect(()=>{document.documentElement.lang=locale;apply(document.body,locale);const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==="characterData")apply(record.target,locale);record.addedNodes.forEach(node=>apply(node,locale))}));observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect()},[locale]);const setLocale=(value:Locale)=>{localStorage.setItem("hse-language",value);setValue(value)};return <Context.Provider value={{locale,setLocale}}>{children}</Context.Provider>}
export function LanguageSwitcher(){const{locale,setLocale}=useContext(Context);return <div className="language-switcher" aria-label="Language">{(["ru","kk","en"] as Locale[]).map(value=><button type="button" className={locale===value?"active":""} key={value} onClick={()=>setLocale(value)}>{value.toUpperCase()}</button>)}</div>}
