"use client";
import { createContext, useContext, useEffect, useState } from "react";
type Locale="ru"|"kk"|"en";
const Context=createContext<{locale:Locale;setLocale:(value:Locale)=>void}>({locale:"ru",setLocale:()=>{}});
const d:Record<string,{kk:string;en:string}>={
"ОПЕРАТИВНЫЙ КОНТРОЛЬ HSE":{kk:"HSE ЖЕДЕЛ БАҚЫЛАУ",en:"HSE OPERATIONAL CONTROL"},"Важное становится":{kk:"Маңызды нәрсе",en:"Important things become"},"видимым вовремя.":{kk:"уақытында көрінеді.",en:"visible in time."},"Сотрудники, допуски, инструктажи, СИЗ, оборудование и документы — в одной системе.":{kk:"Қызметкерлер, рұқсаттар, нұсқамалар, ЖҚҚ, жабдықтар мен құжаттар — бір жүйеде.",en:"Employees, permits, briefings, PPE, equipment and documents — in one system."},"Вход в систему":{kk:"Жүйеге кіру",en:"System access"},
"Оперативный центр":{kk:"Жедел басқару орталығы",en:"Operations center"},"Работники":{kk:"Қызметкерлер",en:"Employees"},"Должности":{kk:"Лауазымдар",en:"Job profiles"},"Оборудование":{kk:"Жабдық",en:"Equipment"},"СИЗ":{kk:"ЖҚҚ",en:"PPE"},"Документы":{kk:"Құжаттар",en:"Documents"},"Задачи":{kk:"Тапсырмалар",en:"Tasks"},"Обучение":{kk:"Оқыту",en:"Learning"},"Команда":{kk:"Команда",en:"Team"},"Журнал действий":{kk:"Әрекеттер журналы",en:"Audit log"},"Тариф и оплата":{kk:"Тариф және төлем",en:"Plan and billing"},"Управление платформой":{kk:"Платформаны басқару",en:"Platform administration"},
"Войти":{kk:"Кіру",en:"Sign in"},"Зарегистрироваться":{kk:"Тіркелу",en:"Sign up"},"Рабочая почта":{kk:"Жұмыс поштасы",en:"Work email"},"Пароль":{kk:"Құпиясөз",en:"Password"},"Имя":{kk:"Аты",en:"Name"},"С возвращением":{kk:"Қош келдіңіз",en:"Welcome back"},"Создать пространство":{kk:"Жұмыс кеңістігін құру",en:"Create workspace"},"Нет аккаунта? Создать":{kk:"Аккаунт жоқ па? Құру",en:"No account? Create one"},"Уже есть аккаунт? Войти":{kk:"Аккаунт бар ма? Кіру",en:"Already registered? Sign in"},
"Что требует внимания сегодня":{kk:"Бүгін нені бақылау қажет",en:"What needs attention today"},"ЕДИНАЯ ОЧЕРЕДЬ":{kk:"БІРЫҢҒАЙ КЕЗЕК",en:"UNIFIED QUEUE"},"Следующие действия":{kk:"Келесі әрекеттер",en:"Next actions"},"Критические":{kk:"Критикалық",en:"Critical"},"Ближайшие сроки":{kk:"Жақын мерзімдер",en:"Upcoming deadlines"},"Активные задачи":{kk:"Белсенді тапсырмалар",en:"Active tasks"},"Обучение просрочено":{kk:"Оқыту мерзімі өтті",en:"Learning overdue"},"События камер":{kk:"Камера оқиғалары",en:"Camera events"},"Состояние системы":{kk:"Жүйе күйі",en:"System health"},"Открыть задачи":{kk:"Тапсырмаларды ашу",en:"Open tasks"},"Добавить сотрудника":{kk:"Қызметкер қосу",en:"Add employee"},"Критические просрочки":{kk:"Критикалық кешігулер",en:"Critical overdue items"},"Активных задач":{kk:"Белсенді тапсырмалар",en:"Active tasks"},"Работников в реестре":{kk:"Тізілімдегі қызметкерлер",en:"Employees in register"},
"Новая программа":{kk:"Жаңа бағдарлама",en:"New program"},"Формат":{kk:"Формат",en:"Format"},"Вид обучения":{kk:"Оқыту түрі",en:"Learning type"},"Название программы":{kk:"Бағдарлама атауы",en:"Program name"},"Инструктаж":{kk:"Нұсқама",en:"Briefing"},"Специальное обучение":{kk:"Арнайы оқыту",en:"Special training"},"Экзамен / проверка знаний":{kk:"Емтихан / білімді тексеру",en:"Exam / knowledge check"},"Вводный":{kk:"Кіріспе",en:"Induction"},"На рабочем месте":{kk:"Жұмыс орнында",en:"Workplace"},"Электробезопасность":{kk:"Электр қауіпсіздігі",en:"Electrical safety"},"Первая помощь":{kk:"Алғашқы көмек",en:"First aid"},"Назначить обучение":{kk:"Оқытуды тағайындау",en:"Assign learning"},"Назначить выбранным":{kk:"Таңдалғандарға тағайындау",en:"Assign selected"},"Срок прохождения":{kk:"Аяқтау мерзімі",en:"Completion deadline"},"Добавить вопрос":{kk:"Сұрақ қосу",en:"Add question"},"Завершить тест":{kk:"Тестті аяқтау",en:"Finish test"},
"Доступ и роли":{kk:"Қолжетімділік және рөлдер",en:"Access and roles"},"Роль":{kk:"Рөл",en:"Role"},"Пригласить":{kk:"Шақыру",en:"Invite"},"Владелец":{kk:"Иесі",en:"Owner"},"Руководитель":{kk:"Басшы",en:"Manager"},"Наблюдатель":{kk:"Бақылаушы",en:"Viewer"},"Удалить доступ":{kk:"Қолжетімділікті жою",en:"Remove access"},
"Новая должность":{kk:"Жаңа лауазым",en:"New job profile"},"Название":{kk:"Атауы",en:"Title"},"Обязательные поля":{kk:"Міндетті өрістер",en:"Required fields"},"Необходимое обучение":{kk:"Қажетті оқыту",en:"Required learning"},"Создать должность":{kk:"Лауазымды құру",en:"Create job profile"},
"Камера устройства":{kk:"Құрылғы камерасы",en:"Device camera"},"Запустить камеру":{kk:"Камераны іске қосу",en:"Start camera"},"Остановить":{kk:"Тоқтату",en:"Stop"},"Нарисовать опасную зону":{kk:"Қауіпті аймақты сызу",en:"Draw danger zone"},"Сохранить контур":{kk:"Контурды сақтау",en:"Save zone"},"Очистить":{kk:"Тазарту",en:"Clear"},"Создать событие":{kk:"Оқиға құру",en:"Create event"},"Создать задачу":{kk:"Тапсырма құру",en:"Create task"},
"Сохранить":{kk:"Сақтау",en:"Save"},"Отмена":{kk:"Бас тарту",en:"Cancel"},"Удалить":{kk:"Жою",en:"Delete"},"Выберите":{kk:"Таңдаңыз",en:"Select"},"Подразделение":{kk:"Бөлімше",en:"Department"},"Должность":{kk:"Лауазым",en:"Position"}
};
Object.assign(d,{
"Выбрать язык":{kk:"Тілді таңдау",en:"Choose language"},"Добавить":{kk:"Қосу",en:"Add"},"Работника":{kk:"Қызметкер",en:"Employee"},"Инвентарь":{kk:"Мүкәммал",en:"Inventory"},"Документ":{kk:"Құжат",en:"Document"},"Задачу":{kk:"Тапсырма",en:"Task"},"Закрыть меню":{kk:"Мәзірді жабу",en:"Close menu"},"Локальное пространство":{kk:"Жергілікті кеңістік",en:"Local workspace"},"Защищено Supabase RLS":{kk:"Supabase RLS арқылы қорғалған",en:"Protected by Supabase RLS"},"Выйти":{kk:"Шығу",en:"Sign out"},"Администратор":{kk:"Әкімші",en:"Administrator"},
"РЕЕСТР И ДОПУСКИ":{kk:"ТІЗІЛІМ ЖӘНЕ РҰҚСАТТАР",en:"REGISTER AND PERMITS"},"Добавить оборудование":{kk:"Жабдық қосу",en:"Add equipment"},"КОНТРОЛЬ СРОКОВ":{kk:"МЕРЗІМДЕРДІ БАҚЫЛАУ",en:"DEADLINE CONTROL"},"Средства индивидуальной защиты":{kk:"Жеке қорғаныс құралдары",en:"Personal protective equipment"},"ВЫДАЧА И ЗАМЕНА":{kk:"БЕРУ ЖӘНЕ АУЫСТЫРУ",en:"ISSUE AND REPLACEMENT"},"Выдать СИЗ":{kk:"ЖҚҚ беру",en:"Issue PPE"},"ЕДИНОЕ ХРАНИЛИЩЕ":{kk:"БІРЫҢҒАЙ ҚОЙМА",en:"UNIFIED STORAGE"},"Загрузить документ":{kk:"Құжат жүктеу",en:"Upload document"},"Загрузка…":{kk:"Жүктелуде…",en:"Uploading…"},"Изменить":{kk:"Өзгерту",en:"Edit"},"В архив":{kk:"Мұрағатқа",en:"Archive"},
"Статус":{kk:"Мәртебе",en:"Status"},"Ф.И.О.":{kk:"Аты-жөні",en:"Full name"},"Инструктаж до":{kk:"Нұсқама мерзімі",en:"Briefing due"},"Наименование":{kk:"Атауы",en:"Name"},"Категория":{kk:"Санат",en:"Category"},"Здание / место":{kk:"Ғимарат / орын",en:"Building / location"},"Следующее обслуживание":{kk:"Келесі қызмет көрсету",en:"Next service"},"Работник":{kk:"Қызметкер",en:"Employee"},"Количество":{kk:"Саны",en:"Quantity"},"Дата замены":{kk:"Ауыстыру күні",en:"Replacement date"},"Недопуск":{kk:"Рұқсат жоқ",en:"Not cleared"},"Скоро срок":{kk:"Мерзімі жақын",en:"Due soon"},"В норме":{kk:"Қалыпты",en:"Compliant"},
"НОВАЯ ЗАПИСЬ":{kk:"ЖАҢА ЖАЗБА",en:"NEW RECORD"},"РЕДАКТИРОВАНИЕ":{kk:"ӨҢДЕУ",en:"EDITING"},"Сотрудник":{kk:"Қызметкер",en:"Employee"},"Дата приёма":{kk:"Қабылданған күні",en:"Hire date"},"Медосмотр до":{kk:"Медтексеру мерзімі",en:"Medical exam due"},"Обучение до":{kk:"Оқыту мерзімі",en:"Training due"},"Здание":{kk:"Ғимарат",en:"Building"},"Место":{kk:"Орын",en:"Location"},"Структурное подразделение":{kk:"Құрылымдық бөлімше",en:"Structural unit"},"Наименование СИЗ":{kk:"ЖҚҚ атауы",en:"PPE item"},"Дата выдачи":{kk:"Берілген күні",en:"Issue date"},"Медосмотр":{kk:"Медициналық тексеру",en:"Medical exam"},
"КОРРЕКТИРУЮЩИЕ ДЕЙСТВИЯ":{kk:"ТҮЗЕТУ ӘРЕКЕТТЕРІ",en:"CORRECTIVE ACTIONS"},"Проблема должна получить ответственного, срок и доказательство закрытия.":{kk:"Әр мәселенің жауаптысы, мерзімі және жабылғанын растайтын дәлелі болуы керек.",en:"Every issue needs an owner, a deadline and proof of closure."},"Новая задача":{kk:"Жаңа тапсырма",en:"New task"},"Что нужно сделать":{kk:"Не істеу керек",en:"What needs to be done"},"Описание":{kk:"Сипаттама",en:"Description"},"Приоритет":{kk:"Басымдық",en:"Priority"},"Низкий":{kk:"Төмен",en:"Low"},"Средний":{kk:"Орташа",en:"Medium"},"Высокий":{kk:"Жоғары",en:"High"},"Критический":{kk:"Критикалық",en:"Critical"},"Срок":{kk:"Мерзім",en:"Deadline"},"Ответственный":{kk:"Жауапты",en:"Responsible"},"Ответственный:":{kk:"Жауапты:",en:"Responsible:"},"Не назначен":{kk:"Тағайындалмаған",en:"Unassigned"},"Создать задачу":{kk:"Тапсырма құру",en:"Create task"},"РАБОЧАЯ ОЧЕРЕДЬ":{kk:"ЖҰМЫС КЕЗЕГІ",en:"WORK QUEUE"},"Новая":{kk:"Жаңа",en:"New"},"В работе":{kk:"Орындалуда",en:"In progress"},"Выполнена":{kk:"Орындалды",en:"Completed"},"Проверена":{kk:"Тексерілді",en:"Verified"},"Без описания":{kk:"Сипаттамасыз",en:"No description"},"Задач пока нет":{kk:"Әзірге тапсырма жоқ",en:"No tasks yet"},"Создайте первое корректирующее действие.":{kk:"Бірінші түзету әрекетін жасаңыз.",en:"Create the first corrective action."},
"ДОСТУП И РОЛИ":{kk:"ҚОЛЖЕТІМДІЛІК ЖӘНЕ РӨЛДЕР",en:"ACCESS AND ROLES"},"Роль предлагает набор разделов, владелец может изменить доступ отдельно.":{kk:"Рөл бөлімдер жиынтығын ұсынады, иесі қолжетімділікті жеке өзгерте алады.",en:"A role suggests sections; the owner can customize access."},"Рабочая почта":{kk:"Жұмыс поштасы",en:"Work email"},"Отправка…":{kk:"Жіберілуде…",en:"Sending…"},"Пригласить":{kk:"Шақыру",en:"Invite"},"Доступ активен":{kk:"Қолжетімділік белсенді",en:"Access active"},"Доступ отключён":{kk:"Қолжетімділік өшірілген",en:"Access disabled"},"Копировать ссылку приглашения":{kk:"Шақыру сілтемесін көшіру",en:"Copy invitation link"},"Удалить доступ":{kk:"Қолжетімділікті жою",en:"Remove access"},
"МОДУЛЬ ОБУЧЕНИЯ":{kk:"ОҚЫТУ МОДУЛІ",en:"LEARNING MODULE"},"Инструктажи, назначения, сроки и проверка знаний по БиОТ.":{kk:"Нұсқамалар, тағайындаулар, мерзімдер және ЕҚ бойынша білімді тексеру.",en:"Briefings, assignments, deadlines and HSE knowledge checks."},"программ":{kk:"бағдарлама",en:"programs"},"активных назначений":{kk:"белсенді тағайындау",en:"active assignments"},"просрочено":{kk:"мерзімі өткен",en:"overdue"},"тестов пройдено":{kk:"тест өтті",en:"tests passed"},"БИБЛИОТЕКА":{kk:"КІТАПХАНА",en:"LIBRARY"},"Назначения":{kk:"Тағайындаулар",en:"Assignments"},"Контроль прохождения":{kk:"Өтуді бақылау",en:"Completion control"},"Программа":{kk:"Бағдарлама",en:"Program"},"Работники · можно выбрать несколько":{kk:"Қызметкерлер · бірнешеуін таңдауға болады",en:"Employees · select multiple"},"Добавить камеру":{kk:"Камера қосу",en:"Add camera"},"Зафиксировать событие":{kk:"Оқиғаны тіркеу",en:"Record event"},
"НЕИЗМЕНЯЕМАЯ ИСТОРИЯ":{kk:"ӨЗГЕРМЕЙТІН ТАРИХ",en:"IMMUTABLE HISTORY"},"Кто, когда и что изменил в системе.":{kk:"Жүйеде кім, қашан және нені өзгертті.",en:"Who changed what in the system and when."},"Действие":{kk:"Әрекет",en:"Action"},"Объект":{kk:"Нысан",en:"Object"},"Пользователь":{kk:"Пайдаланушы",en:"User"},"Дата и время":{kk:"Күні мен уақыты",en:"Date and time"},
"ПОДПИСКА":{kk:"ЖАЗЫЛЫМ",en:"SUBSCRIPTION"},"Вся система.":{kk:"Бүкіл жүйе.",en:"The entire system."},"Без ограничений.":{kk:"Шектеусіз.",en:"Without limits."},"ТЕКУЩИЙ СТАТУС":{kk:"АҒЫМДАҒЫ КҮЙ",en:"CURRENT STATUS"},"Подписка активна":{kk:"Жазылым белсенді",en:"Subscription active"},"Free: до 5 записей":{kk:"Free: 5 жазбаға дейін",en:"Free: up to 5 records"},"Оплатить через Kaspi Pay":{kk:"Kaspi Pay арқылы төлеу",en:"Pay with Kaspi Pay"},
"Активация пользователей, организаций и платежей.":{kk:"Пайдаланушыларды, ұйымдарды және төлемдерді белсендіру.",en:"User, organization and payment activation."},"Организаций":{kk:"Ұйымдар",en:"Organizations"},"Активных пользователей":{kk:"Белсенді пайдаланушылар",en:"Active users"},"Платежей на проверке":{kk:"Тексерілетін төлемдер",en:"Payments to review"},"Пользователи платформы":{kk:"Платформа пайдаланушылары",en:"Platform users"},"Организация":{kk:"Ұйым",en:"Organization"},"Состояние":{kk:"Күй",en:"State"},"Активен":{kk:"Белсенді",en:"Active"},"Отключён":{kk:"Өшірілген",en:"Disabled"},"Отключить":{kk:"Өшіру",en:"Disable"},"Активировать":{kk:"Белсендіру",en:"Activate"},"Сохранение…":{kk:"Сақталуда…",en:"Saving…"},"Комментарий":{kk:"Түсініктеме",en:"Comment"},"Дата":{kk:"Күні",en:"Date"},"Подтвердить":{kk:"Растау",en:"Approve"},"Отклонить":{kk:"Қабылдамау",en:"Reject"}
});
const source=new WeakMap<Node,string>();
function apply(root:Node,locale:Locale){const reverse=new Map<string,string>();for(const[k,v]of Object.entries(d)){reverse.set(k,k);reverse.set(v.kk,k);reverse.set(v.en,k)}const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){const raw=node.textContent||"";if(!raw.trim())continue;const original=source.get(node)||raw;if(!source.has(node))source.set(node,original);let target=original;if(locale!=="ru")for(const[key,value]of Object.entries(d).sort((a,b)=>b[0].length-a[0].length))target=target.replaceAll(key,value[locale]);if(raw!==target)node.textContent=target}const elements=root===document.body?[...document.querySelectorAll("*")]:root instanceof Element?[root,...root.querySelectorAll("*")]:[];for(const el of elements)for(const attr of["placeholder","title","aria-label"]){const value=el.getAttribute(attr),key=value&&reverse.get(value);if(key&&d[key])el.setAttribute(attr,locale==="ru"?key:d[key][locale])}}
export function LanguageProvider({children}:{children:React.ReactNode}){const[locale,setValue]=useState<Locale>("ru");useEffect(()=>{const saved=localStorage.getItem("hse-language") as Locale|null;if(saved&&["ru","kk","en"].includes(saved))queueMicrotask(()=>setValue(saved))},[]);useEffect(()=>{document.documentElement.lang=locale;apply(document.body,locale);const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==="characterData")apply(record.target,locale);record.addedNodes.forEach(node=>apply(node,locale))}));observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect()},[locale]);const setLocale=(value:Locale)=>{localStorage.setItem("hse-language",value);setValue(value)};return <Context.Provider value={{locale,setLocale}}>{children}</Context.Provider>}
export function LanguageSwitcher(){const{locale,setLocale}=useContext(Context);return <details className="language-menu"><summary aria-label="Выбрать язык" title="Выбрать язык"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3.2 4.3 6.2 4.3 9S15 17.8 12 21M12 3C9 6.2 7.7 9.2 7.7 12S9 17.8 12 21"/></svg></summary><div className="language-options">{(["ru","kk","en"] as Locale[]).map(value=><button type="button" className={locale===value?"active":""} key={value} onClick={event=>{setLocale(value);event.currentTarget.closest("details")?.removeAttribute("open")}}><span>{value.toUpperCase()}</span>{value==="ru"?"Русский":value==="kk"?"Қазақша":"English"}</button>)}</div></details>}
