"use client";
import { MouseEvent, useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { VisionCamera, VisionEvent } from "./module-panels";

export function LiveCameraMonitor({cameras,organizationId,supabaseUrl,supabaseKey,onEvent,onZone}:{cameras:VisionCamera[];organizationId:string;supabaseUrl:string;supabaseKey:string;onEvent:(event:VisionEvent)=>void;onZone:(id:string,points:Array<{x:number;y:number}>)=>void}){
 const video=useRef<HTMLVideoElement>(null),analysis=useRef<HTMLCanvasElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|null>(null),previous=useRef<Uint8ClampedArray|null>(null),streak=useRef(0),cooldown=useRef(20);
 const [cameraId,setCameraId]=useState(cameras[0]?.id||""),[deviceId,setDeviceId]=useState(""),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[running,setRunning]=useState(false),[drawing,setDrawing]=useState(false),[alert,setAlert]=useState(""),[sensitivity,setSensitivity]=useState(12);
 const camera=cameras.find(c=>c.id===cameraId),points=camera?.zone_points||[];
 function stop(){if(timer.current)window.clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;previous.current=null;setRunning(false)}
 useEffect(()=>()=>stop(),[]);
 async function start(){try{stop();const media=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:"environment"},audio:false});stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play()}const list=(await navigator.mediaDevices.enumerateDevices()).filter(x=>x.kind==="videoinput");setDevices(list);setDeviceId(media.getVideoTracks()[0]?.getSettings().deviceId||"");setRunning(true);if("Notification"in window&&Notification.permission==="default")await Notification.requestPermission();timer.current=window.setInterval(detect,500)}catch(error){setAlert(error instanceof Error?error.message:"Не удалось открыть камеру")}}
 function inside(x:number,y:number,polygon:Array<{x:number;y:number}>){let hit=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(((a.y>y)!==(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x))hit=!hit}return hit}
 async function detect(){if(!video.current||!analysis.current||points.length<3||video.current.readyState<2)return;cooldown.current++;const canvas=analysis.current,ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return;canvas.width=160;canvas.height=90;ctx.drawImage(video.current,0,0,160,90);const current=ctx.getImageData(0,0,160,90).data;if(previous.current){let changed=0,total=0;for(let y=0;y<90;y+=2)for(let x=0;x<160;x+=2)if(inside(x/160,y/90,points)){const i=(y*160+x)*4,now=(current[i]+current[i+1]+current[i+2])/3,old=(previous.current[i]+previous.current[i+1]+previous.current[i+2])/3;total++;if(Math.abs(now-old)>28)changed++}const ratio=total?changed/total*100:0;streak.current=ratio>=sensitivity?streak.current+1:0;if(streak.current>=2&&cooldown.current>=16){cooldown.current=0;streak.current=0;await emit(ratio)}}previous.current=new Uint8ClampedArray(current)}
 async function emit(confidence:number){if(!camera)return;const message=`Движение в опасной зоне · ${camera.name}`;setAlert(message);if("Notification"in window&&Notification.permission==="granted")new Notification("HSE Radar · Safety Vision",{body:message,icon:"/icon.svg"});const r=await createClient(supabaseUrl,supabaseKey).from("vision_events").insert({organization_id:organizationId,camera_id:camera.id,event_type:"danger_zone",confidence:Math.min(99.99,confidence),status:"new",notes:"Автоматически: движение внутри заданного контура"}).select().single();if(!r.error)onEvent(r.data as VisionEvent)}
 function addPoint(e:MouseEvent<SVGSVGElement>){if(!drawing||!camera)return;const rect=e.currentTarget.getBoundingClientRect(),point={x:Number(((e.clientX-rect.left)/rect.width).toFixed(4)),y:Number(((e.clientY-rect.top)/rect.height).toFixed(4))};onZone(camera.id,[...points,point])}
 async function saveZone(){if(!camera||points.length<3)return;const r=await createClient(supabaseUrl,supabaseKey).from("vision_cameras").update({zone_points:points}).eq("id",camera.id);if(r.error)return setAlert(r.error.message);setDrawing(false);setAlert("Контур опасной зоны сохранён. Детектор активен.")}
 return <section className="panel live-monitor"><div className="panel-title"><div><span className="eyebrow vision">LIVE МОНИТОРИНГ</span><h3>Камера устройства</h3></div><span className={`live-state ${running?"online":""}`}>{running?"● LIVE":"● OFFLINE"}</span></div><div className="live-toolbar"><select value={cameraId} onChange={e=>setCameraId(e.target.value)}><option value="">Камера платформы</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.name} · {c.location}</option>)}</select><select value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="">Камера устройства</option>{devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||"Камера"}</option>)}</select><label>Чувствительность <input type="range" min="4" max="30" value={sensitivity} onChange={e=>setSensitivity(Number(e.target.value))}/></label>{running?<button className="button secondary" onClick={stop}>Остановить</button>:<button className="button dark" disabled={!cameraId} onClick={start}>Запустить камеру</button>}</div><div className="live-frame"><video ref={video} muted playsInline/><svg viewBox="0 0 1000 562" preserveAspectRatio="none" onClick={addPoint}><polygon points={points.map(p=>`${p.x*1000},${p.y*562}`).join(" ")}/>{points.map((p,i)=><circle key={i} cx={p.x*1000} cy={p.y*562} r="8"/>)}</svg>{!running&&<div className="camera-placeholder">Выберите камеру платформы и запустите камеру устройства</div>}</div><canvas ref={analysis} hidden/><div className="live-actions"><button className="button secondary" disabled={!camera||!running} onClick={()=>setDrawing(!drawing)}>{drawing?"Рисование включено":"Нарисовать опасную зону"}</button><button className="button secondary" disabled={!drawing} onClick={()=>camera&&onZone(camera.id,[])}>Очистить</button><button className="button dark" disabled={points.length<3} onClick={saveZone}>Сохранить контур</button><span>{points.length} точек · порог {sensitivity}%</span></div>{alert&&<div className="camera-alert">{alert}<button onClick={()=>setAlert("")}>×</button></div>}</section>
}
