"use client";

import { FormEvent, MouseEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { LiveCameraMonitor } from "./live-camera-monitor";

export type LearningCourse={id:string;title:string;course_type:"instruction"|"knowledge_check";format:"briefing"|"training"|"exam";training_type:string;custom_type_name?:string|null;requires_test:boolean;description?:string|null;passing_score:number;is_active:boolean;created_at:string;question_count?:number};
export type LearningAttempt={id:string;course_id:string;score:number;passed:boolean;completed_at:string};
export type EmployeeOption={id:string;full_name:string;department?:string|null};
export type LearningAssignment={id:string;course_id:string;employee_id:string;due_date:string;status:"assigned"|"in_progress"|"passed"|"failed";score?:number|null;completed_at?:string|null;course_title?:string;course_type?:string;employee_name?:string;department?:string};
export type VisionCamera={id:string;name:string;location:string;stream_url?:string|null;status:"online"|"offline"|"maintenance";zone_points?:Array<{x:number;y:number}>|null;created_at:string};
export type VisionEvent={id:string;camera_id?:string|null;event_type:string;status:string;confidence?:number|null;notes?:string|null;task_id?:string|null;occurred_at:string};

type BaseProps={organizationId:string;supabaseUrl:string;supabaseKey:string};
const courseTypes={instruction:"Инструктаж",knowledge_check:"Проверка знаний"} as const;
const assignmentLabels:Record<string,string>={assigned:"Назначено",in_progress:"В процессе",passed:"Пройдено",failed:"Не пройдено"};
const eventLabels:Record<string,string>={no_helmet:"Без каски",no_vest:"Без жилета",danger_zone:"Опасная зона",blocked_exit:"Перекрыт выход",manual:"Ручная фиксация"};
const eventStatuses:Record<string,string>={new:"Новое",confirmed:"Подтверждено",dismissed:"Ложное",resolved:"Устранено"};
const today=()=>new Date().toISOString().slice(0,10);
function dueTone(date:string,status?:string){if(status==="passed")return"green";const now=new Date();now.setHours(0,0,0,0);const days=Math.round((new Date(`${date}T00:00:00`).getTime()-now.getTime())/86400000);return days<0?"red":days<=7?"yellow":"green"}

export function LearningPanel({organizationId,supabaseUrl,supabaseKey,initialCourses,initialAttempts,initialAssignments,employees}:{initialCourses:LearningCourse[];initialAttempts:LearningAttempt[];initialAssignments:LearningAssignment[];employees:EmployeeOption[]}&BaseProps){
 const [courses,setCourses]=useState(initialCourses),[assignments,setAssignments]=useState(initialAssignments);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[material,setMaterial]=useState<LearningCourse|null>(null);
 const db=()=>createClient(supabaseUrl,supabaseKey);
 async function createAndAssign(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el),format=String(f.get("format")),trainingType=String(f.get("training_type")),custom=String(f.get("custom_type_name")||"").trim(),employeeIds=f.getAll("employee_ids").map(String);if(!employeeIds.length)return setMessage("Выберите хотя бы одного работника.");const title=custom||trainingTitle(trainingType);setBusy(true);setMessage("");let course=courses.find(item=>item.format===format&&item.training_type===trainingType&&String(item.custom_type_name||"")===custom);if(!course){const created=await db().from("learning_courses").insert({organization_id:organizationId,title,format,training_type:trainingType,custom_type_name:custom||null,requires_test:false,course_type:format==="exam"?"knowledge_check":"instruction",description:String(f.get("description")||""),passing_score:80}).select().single();if(created.error){setBusy(false);return setMessage(created.error.message)}course={...(created.data as LearningCourse),question_count:0};setCourses(value=>[course!,...value])}const rows=employeeIds.map(employeeId=>({organization_id:organizationId,course_id:course!.id,employee_id:employeeId,due_date:String(f.get("due_date"))}));const assigned=await db().from("learning_assignments").upsert(rows,{onConflict:"course_id,employee_id"}).select("id,course_id,employee_id,due_date,status,score,completed_at");setBusy(false);if(assigned.error)return setMessage(assigned.error.message);const added=(assigned.data||[]).map(row=>{const employee=employees.find(item=>item.id===row.employee_id);return{...row,course_title:course!.title,course_type:course!.course_type,employee_name:employee?.full_name,department:employee?.department||undefined} as LearningAssignment});setAssignments(value=>[...added,...value.filter(old=>!added.some(item=>item.id===old.id))]);el.reset();setMessage(`Обучение назначено: ${employeeIds.length} работников.`)}
 async function updateAssignment(id:string,patch:Record<string,unknown>){setBusy(true);setMessage("");if(patch.status==="passed"||patch.status==="failed")patch.completed_at=new Date().toISOString();if(patch.status==="assigned"||patch.status==="in_progress")patch.completed_at=null;const r=await db().from("learning_assignments").update(patch).eq("id",id).select("id,course_id,employee_id,due_date,status,score,completed_at").single();setBusy(false);if(r.error)return setMessage(r.error.message);setAssignments(v=>v.map(a=>a.id===id?{...a,...r.data}:a))}
 async function renameCourse(course:LearningCourse){const title=prompt("Новое название программы",course.title)?.trim();if(!title||title===course.title)return;setBusy(true);const r=await db().from("learning_courses").update({title}).eq("id",course.id).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCourses(v=>v.map(item=>item.id===course.id?{...item,title}:item));setMessage("Программа обновлена.")}
 async function removeCourse(course:LearningCourse){if(!confirm("Удалить программу и связанные назначения?"))return;setBusy(true);const r=await db().from("learning_courses").delete().eq("id",course.id);setBusy(false);if(r.error)return setMessage(r.error.message);setCourses(v=>v.filter(item=>item.id!==course.id));setAssignments(v=>v.filter(item=>item.course_id!==course.id));setMessage("Программа удалена.")}
 return <><section className="page-heading compact"><div><span className="eyebrow">МОДУЛЬ ОБУЧЕНИЯ</span><h1>Обучение</h1><p>Назначение инструктажей, обучения и проверок знаний. Тестирование проводится через Google Forms.</p></div></section>{message&&<div className="inline-notice">{message}</div>}
 <section className="learning-summary"><Summary value={courses.length} label="видов обучения"/><Summary value={assignments.filter(a=>a.status!=="passed").length} label="активных назначений"/><Summary value={assignments.filter(a=>dueTone(a.due_date,a.status)==="red").length} label="просрочено"/><Summary value={initialAttempts.filter(a=>a.passed).length} label="пройдено ранее"/></section>
 <section className="module-grid"><AssignmentForm busy={busy} employees={employees} submit={createAndAssign}/><section className="panel assignment-list"><PanelTitle eyebrow="НАЗНАЧЕНИЯ" title="Контроль прохождения"/>{assignments.length?assignments.map(a=><article className={`assignment-row deadline-${dueTone(a.due_date,a.status)}`} key={a.id}><div><span className={`status ${dueTone(a.due_date,a.status)}`}>{assignmentLabels[a.status]}</span><strong>{a.employee_name||"Работник"}</strong><small>{a.course_title||"Обучение"}{a.department?` · ${a.department}`:""}</small></div><label>Срок<input type="date" value={a.due_date} disabled={busy} onChange={e=>updateAssignment(a.id,{due_date:e.target.value,reminder_sent_at:null})}/></label><select value={a.status} disabled={busy} onChange={e=>updateAssignment(a.id,{status:e.target.value})}><option value="assigned">Назначено</option><option value="in_progress">В процессе</option><option value="passed">Пройдено</option><option value="failed">Не пройдено</option></select></article>):<Empty text="Назначений пока нет"/>}</section></section>
 <section className="panel module-list learning-library"><PanelTitle eyebrow="СПРАВОЧНИК" title={`${courses.length} видов обучения`}/>{courses.length?courses.map(c=><article className="module-row" key={c.id}><div><span className={`module-dot ${c.course_type}`}/><strong>{c.title}</strong><small>{courseTypes[c.course_type]} · {c.format==="briefing"?"инструктаж":c.format==="training"?"специальное обучение":"проверка знаний"}</small></div><div className="module-actions">{c.description&&<button type="button" className="button secondary" onClick={()=>setMaterial(c)}>Материал</button>}<button type="button" onClick={()=>renameCourse(c)} disabled={busy}>Изменить</button><button type="button" className="danger-link" onClick={()=>removeCourse(c)} disabled={busy}>Удалить</button></div></article>):<Empty text="Назначьте первое обучение"/>}</section>
 {material&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setMaterial(null)}}><div className="modal material-modal"><ModalHead eyebrow="МАТЕРИАЛ" title={material.title} close={()=>setMaterial(null)}/><div className="material-copy">{material.description||"Материал ещё не добавлен."}</div><div className="modal-actions"><button className="button dark" onClick={()=>setMaterial(null)}>Закрыть</button></div></div></div>}</>
}

export function SafetyVisionPanel({organizationId,supabaseUrl,supabaseKey,initialCameras,initialEvents}:{initialCameras:VisionCamera[];initialEvents:VisionEvent[]}&BaseProps){
 const [cameras,setCameras]=useState(initialCameras),[events,setEvents]=useState(initialEvents),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editingZone,setEditingZone]=useState<string|null>(null);
 useEffect(()=>{const close=(event:PointerEvent)=>{const target=event.target as HTMLElement;if(target.classList.contains("modal-backdrop"))setEditingZone(null)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
 const selected=useMemo(()=>cameras.find(c=>c.id===editingZone),[cameras,editingZone]),db=()=>createClient(supabaseUrl,supabaseKey);
 async function createCamera(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const r=await db().from("vision_cameras").insert({organization_id:organizationId,name:String(f.get("name")),location:String(f.get("location")),stream_url:String(f.get("stream_url")||"")||null,status:String(f.get("status"))}).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCameras(v=>[r.data as VisionCamera,...v]);el.reset();setMessage("Камера добавлена.")}
 async function setCameraStatus(id:string,status:string){setBusy(true);const r=await db().from("vision_cameras").update({status}).eq("id",id).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCameras(v=>v.map(c=>c.id===id?r.data as VisionCamera:c))}
 async function removeCamera(camera:VisionCamera){if(!confirm("Удалить камеру и связанные события?"))return;setBusy(true);const r=await db().from("vision_cameras").delete().eq("id",camera.id);setBusy(false);if(r.error)return setMessage(r.error.message);setCameras(v=>v.filter(item=>item.id!==camera.id));setMessage("Камера удалена.")}
 function addPoint(e:MouseEvent<HTMLDivElement>){if(!selected)return;const rect=e.currentTarget.getBoundingClientRect(),point={x:Number(((e.clientX-rect.left)/rect.width).toFixed(4)),y:Number(((e.clientY-rect.top)/rect.height).toFixed(4))};setCameras(v=>v.map(c=>c.id===selected.id?{...c,zone_points:[...(c.zone_points||[]),point]}:c))}
 async function saveZone(){if(!selected)return;const camera=cameras.find(c=>c.id===selected.id);setBusy(true);const r=await db().from("vision_cameras").update({zone_points:camera?.zone_points||[]}).eq("id",selected.id);setBusy(false);if(r.error)return setMessage(r.error.message);setEditingZone(null);setMessage("Опасная зона сохранена.")}
 async function createEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const r=await db().from("vision_events").insert({organization_id:organizationId,camera_id:String(f.get("camera_id")),event_type:String(f.get("event_type")),notes:String(f.get("notes")||"")||null,status:"new"}).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setEvents(v=>[r.data as VisionEvent,...v]);el.reset();setMessage("Событие зафиксировано.")}
 async function updateEvent(id:string,status:string){setBusy(true);const r=await db().from("vision_events").update({status,resolved_at:status==="resolved"?new Date().toISOString():null}).eq("id",id).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setEvents(v=>v.map(x=>x.id===id?r.data as VisionEvent:x))}
 async function makeTask(event:VisionEvent){setBusy(true);setMessage("");const camera=cameras.find(c=>c.id===event.camera_id),r=await db().from("tasks").insert({organization_id:organizationId,title:`Safety Vision: ${eventLabels[event.event_type]||event.event_type}`,description:`${camera?.name||"Камера"} · ${camera?.location||"Локация не указана"}${event.notes?` · ${event.notes}`:""}`,priority:"high",status:"open",due_date:today(),source_type:"vision_event",source_id:event.id}).select("id").single();if(r.error){setBusy(false);return setMessage(r.error.message)}const u=await db().from("vision_events").update({task_id:r.data.id,status:"confirmed"}).eq("id",event.id).select().single();setBusy(false);if(u.error)return setMessage(u.error.message);setEvents(v=>v.map(x=>x.id===event.id?u.data as VisionEvent:x));setMessage("Корректирующая задача создана.")}
 return <><section className="page-heading compact"><div><span className="eyebrow vision">МОДУЛЬ КОМПЬЮТЕРНОГО ЗРЕНИЯ</span><h1>Safety Vision</h1><p>Камеры, опасные зоны, проверка событий и корректирующие задачи.</p></div></section>{message&&<div className="inline-notice">{message}</div>}
 <section className="learning-summary vision-summary"><Summary value={cameras.filter(c=>c.status==="online").length} label="камер онлайн"/><Summary value={events.filter(e=>e.status==="new").length} label="новых событий"/><Summary value={events.filter(e=>e.status==="confirmed").length} label="подтверждено"/><Summary value={events.filter(e=>e.status==="resolved").length} label="устранено"/></section><LiveCameraMonitor cameras={cameras} organizationId={organizationId} supabaseUrl={supabaseUrl} supabaseKey={supabaseKey} onEvent={event=>setEvents(v=>[event,...v])} onZone={(id,zone_points)=>setCameras(v=>v.map(c=>c.id===id?{...c,zone_points}:c))}/>
 <section className="module-grid"><CameraForm busy={busy} submit={createCamera}/><section className="panel module-list"><PanelTitle eyebrow="КАМЕРЫ" title={`${cameras.length} подключено`} vision/>{cameras.length?cameras.map(c=><article className="module-row camera-row" key={c.id}><div><span className={`camera-state ${c.status}`}/><strong>{c.name}</strong><small>{c.location} · точек зоны {c.zone_points?.length||0}{c.stream_url?" · поток задан":""}</small></div><select value={c.status} disabled={busy} onChange={e=>setCameraStatus(c.id,e.target.value)}><option value="online">Онлайн</option><option value="offline">Офлайн</option><option value="maintenance">Обслуживание</option></select><div className="module-actions"><button className="button secondary" onClick={()=>setEditingZone(c.id)}>Опасная зона</button><button className="danger-link" onClick={()=>removeCamera(c)} disabled={busy}>Удалить</button></div></article>):<Empty text="Добавьте первую камеру"/>}</section></section>
 <section className="module-grid lower"><EventForm cameras={cameras} busy={busy} submit={createEvent}/><section className="panel event-list"><PanelTitle eyebrow="СОБЫТИЯ" title="Проверка нарушений" vision/>{events.length?events.slice(0,15).map(x=><article className="event-row" key={x.id}><div><span className={`status ${x.status==="dismissed"||x.status==="resolved"?"green":x.status==="confirmed"?"yellow":"red"}`}>{eventStatuses[x.status]||x.status}</span><strong>{eventLabels[x.event_type]||x.event_type}</strong><small>{cameras.find(c=>c.id===x.camera_id)?.name||"Камера"}{x.notes?` · ${x.notes}`:""}</small></div><time>{new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.occurred_at))}</time><select value={x.status} disabled={busy} onChange={e=>updateEvent(x.id,e.target.value)}><option value="new">Новое</option><option value="confirmed">Подтверждено</option><option value="dismissed">Ложное</option><option value="resolved">Устранено</option></select><button className="button secondary" disabled={busy||Boolean(x.task_id)} onClick={()=>makeTask(x)}>{x.task_id?"Задача создана":"Создать задачу"}</button></article>):<Empty text="Событий пока нет"/>}</section></section>
 {selected&&<div className="modal-backdrop"><div className="modal zone-modal"><ModalHead eyebrow="ОПАСНАЯ ЗОНА" title={selected.name} close={()=>setEditingZone(null)}/><p className="muted">Нажимайте по кадру, чтобы построить многоугольник по часовой стрелке.</p><div className="zone-canvas" onClick={addPoint}><svg viewBox="0 0 1000 560" preserveAspectRatio="none"><polygon points={(selected.zone_points||[]).map(p=>`${p.x*1000},${p.y*560}`).join(" ")}/>{(selected.zone_points||[]).map((p,i)=><circle key={i} cx={p.x*1000} cy={p.y*560} r="8"/>)}</svg><span>Предпросмотр камеры</span></div><div className="modal-actions"><button className="button secondary" onClick={()=>setCameras(v=>v.map(c=>c.id===selected.id?{...c,zone_points:[]}:c))}>Очистить</button><button className="button dark" onClick={saveZone} disabled={busy||(selected.zone_points?.length||0)<3}>Сохранить зону</button></div></div></div>}</>
}

function Summary({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function PanelTitle({eyebrow,title,vision=false}:{eyebrow:string;title:string;vision?:boolean}){return <div className="panel-title"><div><span className={vision?"eyebrow vision":"eyebrow"}>{eyebrow}</span><h3>{title}</h3></div></div>}
function ModalHead({eyebrow,title,close}:{eyebrow:string;title:string;close:()=>void}){return <div className="modal-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" onClick={close}>×</button></div>}
const trainingNames:Record<string,string>={intro:"Вводный",primary_workplace:"Первичный на рабочем месте",repeat:"Повторный",unscheduled:"Внеплановый",targeted:"Целевой",electrical:"Электробезопасность",ptm:"ПТМ",first_aid:"Первая помощь",industrial_safety:"Промышленная безопасность",other:"Другое",hse_exam:"Экзамен (проверка знаний по БиОТ)"};
function trainingTitle(code:string){return trainingNames[code]||"Обучение"}
function AssignmentForm({busy,employees,submit}:{busy:boolean;employees:EmployeeOption[];submit:(e:FormEvent<HTMLFormElement>)=>void}){const[format,setFormat]=useState("briefing"),[trainingType,setTrainingType]=useState("intro");const options=format==="briefing"?[["intro","Вводный"],["primary_workplace","Первичный на рабочем месте"],["repeat","Повторный"],["unscheduled","Внеплановый"],["targeted","Целевой"]]:format==="training"?[["electrical","Электробезопасность"],["ptm","ПТМ"],["first_aid","Первая помощь"],["industrial_safety","ПромБез"],["other","Другое"]]:[["hse_exam","Экзамен (проверка знаний по БиОТ)"]];function changeFormat(value:string){setFormat(value);setTrainingType(value==="briefing"?"intro":value==="training"?"electrical":"hse_exam")}return <form className="panel compact-form assignment-form" onSubmit={submit}><h3>Назначить обучение</h3><label>Формат<select name="format" value={format} onChange={e=>changeFormat(e.target.value)}><option value="briefing">Инструктаж</option><option value="training">Специальное обучение</option><option value="exam">Экзамен / проверка знаний</option></select></label><label>Вид обучения<select name="training_type" value={trainingType} onChange={event=>setTrainingType(event.target.value)}>{options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{trainingType==="other"&&<label>Название другого обучения<input name="custom_type_name" required placeholder="Укажите название"/></label>}<label>Материал или ссылка Google Forms<textarea name="description" rows={3} placeholder="Необязательно"/></label><fieldset className="employee-picker"><legend>Работники · выберите одного или нескольких</legend>{employees.map(employee=><label key={employee.id}><input type="checkbox" name="employee_ids" value={employee.id}/><span>{employee.full_name}<small>{employee.department||"Без подразделения"}</small></span></label>)}</fieldset><label>Срок прохождения<input name="due_date" type="date" min={today()} required/></label><button className="button dark" disabled={busy||!employees.length}>{busy?"Назначение…":"Назначить выбранным"}</button></form>}
function CameraForm({busy,submit}:{busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Добавить камеру</h3><label>Название<input name="name" required placeholder="Камера 01"/></label><label>Расположение<input name="location" required placeholder="Склад · въезд"/></label><label>Адрес потока<input name="stream_url" placeholder="RTSP/HTTPS — хранится закрыто"/></label><label>Состояние<select name="status" defaultValue="offline"><option value="online">Онлайн</option><option value="offline">Офлайн</option><option value="maintenance">Обслуживание</option></select></label><button className="button dark" disabled={busy}>Добавить камеру</button></form>}
function EventForm({cameras,busy,submit}:{cameras:VisionCamera[];busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Зафиксировать событие</h3><label>Камера<select name="camera_id" required><option value="">Выберите</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Нарушение<select name="event_type" defaultValue="no_helmet">{Object.entries(eventLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Комментарий<textarea name="notes" rows={3} placeholder="Что произошло и что видно на записи"/></label><button className="button dark" disabled={busy}>Создать событие</button></form>}
function Empty({text}:{text:string}){return <div className="module-empty">{text}</div>}
