"use client";

import { FormEvent, MouseEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type LearningCourse={id:string;title:string;course_type:"instruction"|"knowledge_check";description?:string|null;passing_score:number;is_active:boolean;created_at:string;question_count?:number};
export type LearningAttempt={id:string;course_id:string;score:number;passed:boolean;completed_at:string};
export type EmployeeOption={id:string;full_name:string;department?:string|null};
export type LearningAssignment={id:string;course_id:string;employee_id:string;due_date:string;status:"assigned"|"in_progress"|"passed"|"failed";score?:number|null;completed_at?:string|null;course_title?:string;course_type?:string;employee_name?:string;department?:string};
export type VisionCamera={id:string;name:string;location:string;stream_url?:string|null;status:"online"|"offline"|"maintenance";zone_points?:Array<{x:number;y:number}>|null;created_at:string};
export type VisionEvent={id:string;camera_id?:string|null;event_type:string;status:string;confidence?:number|null;notes?:string|null;task_id?:string|null;occurred_at:string};

type BaseProps={organizationId:string;supabaseUrl:string;supabaseKey:string};
const courseTypes={instruction:"Инструктаж",knowledge_check:"Проверка знаний"} as const;
const assignmentLabels:Record<string,string>={assigned:"Назначено",in_progress:"В процессе",passed:"Пройдено",failed:"Не пройдено"};
const eventLabels:Record<string,string>={no_helmet:"Без каски",no_vest:"Без жилета",danger_zone:"Опасная зона",blocked_exit:"Перекрыт выход",manual:"Ручная фиксация"};
const eventStatuses:Record<string,string>={new:"Новое",confirmed:"Подтверждено",dismissed:"Ложное",resolved:"Устранено"};
const today=()=>new Date().toISOString().slice(0,10);
function dueTone(date:string,status?:string){if(status==="passed")return"green";const now=new Date();now.setHours(0,0,0,0);const days=Math.round((new Date(`${date}T00:00:00`).getTime()-now.getTime())/86400000);return days<0?"red":days<=7?"yellow":"green"}

export function LearningPanel({organizationId,supabaseUrl,supabaseKey,initialCourses,initialAttempts,initialAssignments,employees}:{initialCourses:LearningCourse[];initialAttempts:LearningAttempt[];initialAssignments:LearningAssignment[];employees:EmployeeOption[]}&BaseProps){
 const [courses,setCourses]=useState(initialCourses),[attempts,setAttempts]=useState(initialAttempts),[assignments,setAssignments]=useState(initialAssignments);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[material,setMaterial]=useState<LearningCourse|null>(null);
 const [test,setTest]=useState<{course:LearningCourse;questions:Array<{id:string;question:string;options:string[]}>}|null>(null);
 const db=()=>createClient(supabaseUrl,supabaseKey);
 async function createCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const r=await db().from("learning_courses").insert({organization_id:organizationId,title:String(f.get("title")),course_type:String(f.get("course_type")),description:String(f.get("description")||""),passing_score:Number(f.get("passing_score")||80)}).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCourses(v=>[{...(r.data as LearningCourse),question_count:0},...v]);el.reset();setMessage("Программа создана.")}
 async function addQuestion(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el),courseId=String(f.get("course_id"));setBusy(true);setMessage("");const r=await db().from("learning_questions").insert({organization_id:organizationId,course_id:courseId,question:String(f.get("question")),options:[String(f.get("option_1")),String(f.get("option_2")),String(f.get("option_3"))],correct_option:Number(f.get("correct_option"))});setBusy(false);if(r.error)return setMessage(r.error.message);setCourses(v=>v.map(c=>c.id===courseId?{...c,question_count:(c.question_count||0)+1}:c));el.reset();setMessage("Вопрос добавлен.")}
 async function assignCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el),courseId=String(f.get("course_id")),employeeId=String(f.get("employee_id"));setBusy(true);setMessage("");const r=await db().from("learning_assignments").insert({organization_id:organizationId,course_id:courseId,employee_id:employeeId,due_date:String(f.get("due_date"))}).select("id,course_id,employee_id,due_date,status,score,completed_at").single();setBusy(false);if(r.error)return setMessage(r.error.code==="23505"?"Эта программа уже назначена выбранному работнику.":r.error.message);const c=courses.find(x=>x.id===courseId),employee=employees.find(x=>x.id===employeeId);setAssignments(v=>[{...(r.data as LearningAssignment),course_title:c?.title,course_type:c?.course_type,employee_name:employee?.full_name,department:employee?.department||undefined},...v]);el.reset();setMessage("Обучение назначено.")}
 async function updateAssignment(id:string,patch:Record<string,unknown>){setBusy(true);setMessage("");if(patch.status==="passed"||patch.status==="failed")patch.completed_at=new Date().toISOString();if(patch.status==="assigned"||patch.status==="in_progress")patch.completed_at=null;const r=await db().from("learning_assignments").update(patch).eq("id",id).select("id,course_id,employee_id,due_date,status,score,completed_at").single();setBusy(false);if(r.error)return setMessage(r.error.message);setAssignments(v=>v.map(a=>a.id===id?{...a,...r.data}:a))}
 async function startTest(course:LearningCourse){setBusy(true);setMessage("");const r=await fetch(`/api/learning/test?courseId=${encodeURIComponent(course.id)}`),body=await r.json();setBusy(false);if(!r.ok)return setMessage(body.error||"Не удалось открыть тест");if(!body.questions?.length)return setMessage("В тесте ещё нет вопросов.");setTest({course,questions:body.questions})}
 async function submitTest(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!test)return;const f=new FormData(e.currentTarget),answers=Object.fromEntries(test.questions.map(q=>[q.id,Number(f.get(q.id))]));setBusy(true);const r=await fetch("/api/learning/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId:test.course.id,answers})}),body=await r.json();setBusy(false);if(!r.ok)return setMessage(body.error||"Не удалось сохранить результат");setAttempts(v=>[body.attempt,...v]);setMessage(body.passed?`Проверка пройдена: ${body.score}%`:`Проверка не пройдена: ${body.score}%`);setTest(null)}
 return <><section className="page-heading compact"><div><span className="eyebrow">МОДУЛЬ ОБУЧЕНИЯ</span><h1>Обучение</h1><p>Инструктажи, назначения, сроки и проверка знаний по БиОТ.</p></div></section>{message&&<div className="inline-notice">{message}</div>}
 <section className="learning-summary"><Summary value={courses.length} label="программ"/><Summary value={assignments.filter(a=>a.status!=="passed").length} label="активных назначений"/><Summary value={assignments.filter(a=>dueTone(a.due_date,a.status)==="red").length} label="просрочено"/><Summary value={attempts.filter(a=>a.passed).length} label="тестов пройдено"/></section>
 <section className="module-grid"><CourseForm busy={busy} submit={createCourse}/><section className="panel module-list"><PanelTitle eyebrow="БИБЛИОТЕКА" title={`${courses.length} программ`}/>{courses.length?courses.map(c=><article className="module-row" key={c.id}><div><span className={`module-dot ${c.course_type}`}/><strong>{c.title}</strong><small>{courseTypes[c.course_type]} · проходной балл {c.passing_score}% · вопросов {c.question_count||0}</small></div><button type="button" className="button secondary" onClick={()=>c.course_type==="knowledge_check"?startTest(c):setMaterial(c)} disabled={busy}>{c.course_type==="knowledge_check"?"Пройти тест":"Открыть материал"}</button></article>):<Empty text="Создайте первую программу"/>}</section></section>
 <section className="module-grid lower"><form className="panel compact-form" onSubmit={assignCourse}><h3>Назначить обучение</h3><label>Программа<select name="course_id" required><option value="">Выберите</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Работник<select name="employee_id" required><option value="">Выберите</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}{x.department?` · ${x.department}`:""}</option>)}</select></label><label>Срок прохождения<input name="due_date" type="date" min={today()} required/></label><button className="button dark" disabled={busy||!courses.length||!employees.length}>Назначить</button></form><section className="panel assignment-list"><PanelTitle eyebrow="НАЗНАЧЕНИЯ" title="Контроль прохождения"/>{assignments.length?assignments.map(a=><article className={`assignment-row deadline-${dueTone(a.due_date,a.status)}`} key={a.id}><div><span className={`status ${dueTone(a.due_date,a.status)}`}>{assignmentLabels[a.status]}</span><strong>{a.employee_name||"Работник"}</strong><small>{a.course_title||"Программа"}{a.department?` · ${a.department}`:""}</small></div><label>Срок<input type="date" value={a.due_date} disabled={busy} onChange={e=>updateAssignment(a.id,{due_date:e.target.value,reminder_sent_at:null})}/></label><select value={a.status} disabled={busy} onChange={e=>updateAssignment(a.id,{status:e.target.value})}><option value="assigned">Назначено</option><option value="in_progress">В процессе</option><option value="passed">Пройдено</option><option value="failed">Не пройдено</option></select></article>):<Empty text="Назначений пока нет"/>}</section></section>
 <section className="module-grid lower"><QuestionForm courses={courses} busy={busy} submit={addQuestion}/><section className="panel"><PanelTitle eyebrow="РЕЗУЛЬТАТЫ" title="Последние попытки"/>{attempts.length?attempts.slice(0,10).map(a=><div className="attempt-row" key={a.id}><span className={`status ${a.passed?"green":"red"}`}>{a.passed?"Пройдено":"Не пройдено"}</span><strong>{courses.find(c=>c.id===a.course_id)?.title||"Проверка знаний"}</strong><time>{a.score}% · {new Intl.DateTimeFormat("ru-RU").format(new Date(a.completed_at))}</time></div>):<Empty text="Результаты появятся после первого теста"/>}</section></section>
 {material&&<div className="modal-backdrop"><div className="modal material-modal"><ModalHead eyebrow="МАТЕРИАЛ ИНСТРУКТАЖА" title={material.title} close={()=>setMaterial(null)}/><div className="material-copy">{material.description||"Материал ещё не добавлен."}</div><div className="modal-actions"><button className="button dark" onClick={()=>setMaterial(null)}>Ознакомился</button></div></div></div>}
 {test&&<div className="modal-backdrop"><form className="modal test-modal" onSubmit={submitTest}><ModalHead eyebrow="ПРОВЕРКА ЗНАНИЙ" title={test.course.title} close={()=>setTest(null)}/>{test.questions.map((q,n)=><fieldset className="question" key={q.id}><legend>{n+1}. {q.question}</legend>{q.options.map((o,i)=><label key={i}><input type="radio" name={q.id} value={i} required/>{o}</label>)}</fieldset>)}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setTest(null)}>Закрыть</button><button className="button dark" disabled={busy}>Завершить тест</button></div></form></div>}</>
}

export function SafetyVisionPanel({organizationId,supabaseUrl,supabaseKey,initialCameras,initialEvents}:{initialCameras:VisionCamera[];initialEvents:VisionEvent[]}&BaseProps){
 const [cameras,setCameras]=useState(initialCameras),[events,setEvents]=useState(initialEvents),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editingZone,setEditingZone]=useState<string|null>(null);
 const selected=useMemo(()=>cameras.find(c=>c.id===editingZone),[cameras,editingZone]),db=()=>createClient(supabaseUrl,supabaseKey);
 async function createCamera(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const r=await db().from("vision_cameras").insert({organization_id:organizationId,name:String(f.get("name")),location:String(f.get("location")),stream_url:String(f.get("stream_url")||"")||null,status:String(f.get("status"))}).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCameras(v=>[r.data as VisionCamera,...v]);el.reset();setMessage("Камера добавлена.")}
 async function setCameraStatus(id:string,status:string){setBusy(true);const r=await db().from("vision_cameras").update({status}).eq("id",id).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setCameras(v=>v.map(c=>c.id===id?r.data as VisionCamera:c))}
 function addPoint(e:MouseEvent<HTMLDivElement>){if(!selected)return;const rect=e.currentTarget.getBoundingClientRect(),point={x:Number(((e.clientX-rect.left)/rect.width).toFixed(4)),y:Number(((e.clientY-rect.top)/rect.height).toFixed(4))};setCameras(v=>v.map(c=>c.id===selected.id?{...c,zone_points:[...(c.zone_points||[]),point]}:c))}
 async function saveZone(){if(!selected)return;const camera=cameras.find(c=>c.id===selected.id);setBusy(true);const r=await db().from("vision_cameras").update({zone_points:camera?.zone_points||[]}).eq("id",selected.id);setBusy(false);if(r.error)return setMessage(r.error.message);setEditingZone(null);setMessage("Опасная зона сохранена.")}
 async function createEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const r=await db().from("vision_events").insert({organization_id:organizationId,camera_id:String(f.get("camera_id")),event_type:String(f.get("event_type")),notes:String(f.get("notes")||"")||null,status:"new"}).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setEvents(v=>[r.data as VisionEvent,...v]);el.reset();setMessage("Событие зафиксировано.")}
 async function updateEvent(id:string,status:string){setBusy(true);const r=await db().from("vision_events").update({status,resolved_at:status==="resolved"?new Date().toISOString():null}).eq("id",id).select().single();setBusy(false);if(r.error)return setMessage(r.error.message);setEvents(v=>v.map(x=>x.id===id?r.data as VisionEvent:x))}
 async function makeTask(event:VisionEvent){setBusy(true);setMessage("");const camera=cameras.find(c=>c.id===event.camera_id),r=await db().from("tasks").insert({organization_id:organizationId,title:`Safety Vision: ${eventLabels[event.event_type]||event.event_type}`,description:`${camera?.name||"Камера"} · ${camera?.location||"Локация не указана"}${event.notes?` · ${event.notes}`:""}`,priority:"high",status:"open",due_date:today(),source_type:"vision_event",source_id:event.id}).select("id").single();if(r.error){setBusy(false);return setMessage(r.error.message)}const u=await db().from("vision_events").update({task_id:r.data.id,status:"confirmed"}).eq("id",event.id).select().single();setBusy(false);if(u.error)return setMessage(u.error.message);setEvents(v=>v.map(x=>x.id===event.id?u.data as VisionEvent:x));setMessage("Корректирующая задача создана.")}
 return <><section className="page-heading compact"><div><span className="eyebrow vision">МОДУЛЬ КОМПЬЮТЕРНОГО ЗРЕНИЯ</span><h1>Safety Vision</h1><p>Камеры, опасные зоны, проверка событий и корректирующие задачи.</p></div></section>{message&&<div className="inline-notice">{message}</div>}
 <section className="learning-summary vision-summary"><Summary value={cameras.filter(c=>c.status==="online").length} label="камер онлайн"/><Summary value={events.filter(e=>e.status==="new").length} label="новых событий"/><Summary value={events.filter(e=>e.status==="confirmed").length} label="подтверждено"/><Summary value={events.filter(e=>e.status==="resolved").length} label="устранено"/></section>
 <section className="module-grid"><CameraForm busy={busy} submit={createCamera}/><section className="panel module-list"><PanelTitle eyebrow="КАМЕРЫ" title={`${cameras.length} подключено`} vision/>{cameras.length?cameras.map(c=><article className="module-row camera-row" key={c.id}><div><span className={`camera-state ${c.status}`}/><strong>{c.name}</strong><small>{c.location} · точек зоны {c.zone_points?.length||0}{c.stream_url?" · поток задан":""}</small></div><select value={c.status} disabled={busy} onChange={e=>setCameraStatus(c.id,e.target.value)}><option value="online">Онлайн</option><option value="offline">Офлайн</option><option value="maintenance">Обслуживание</option></select><button className="button secondary" onClick={()=>setEditingZone(c.id)}>Опасная зона</button></article>):<Empty text="Добавьте первую камеру"/>}</section></section>
 <section className="module-grid lower"><EventForm cameras={cameras} busy={busy} submit={createEvent}/><section className="panel event-list"><PanelTitle eyebrow="СОБЫТИЯ" title="Проверка нарушений" vision/>{events.length?events.slice(0,15).map(x=><article className="event-row" key={x.id}><div><span className={`status ${x.status==="dismissed"||x.status==="resolved"?"green":x.status==="confirmed"?"yellow":"red"}`}>{eventStatuses[x.status]||x.status}</span><strong>{eventLabels[x.event_type]||x.event_type}</strong><small>{cameras.find(c=>c.id===x.camera_id)?.name||"Камера"}{x.notes?` · ${x.notes}`:""}</small></div><time>{new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.occurred_at))}</time><select value={x.status} disabled={busy} onChange={e=>updateEvent(x.id,e.target.value)}><option value="new">Новое</option><option value="confirmed">Подтверждено</option><option value="dismissed">Ложное</option><option value="resolved">Устранено</option></select><button className="button secondary" disabled={busy||Boolean(x.task_id)} onClick={()=>makeTask(x)}>{x.task_id?"Задача создана":"Создать задачу"}</button></article>):<Empty text="Событий пока нет"/>}</section></section>
 {selected&&<div className="modal-backdrop"><div className="modal zone-modal"><ModalHead eyebrow="ОПАСНАЯ ЗОНА" title={selected.name} close={()=>setEditingZone(null)}/><p className="muted">Нажимайте по кадру, чтобы построить многоугольник по часовой стрелке.</p><div className="zone-canvas" onClick={addPoint}><svg viewBox="0 0 1000 560" preserveAspectRatio="none"><polygon points={(selected.zone_points||[]).map(p=>`${p.x*1000},${p.y*560}`).join(" ")}/>{(selected.zone_points||[]).map((p,i)=><circle key={i} cx={p.x*1000} cy={p.y*560} r="8"/>)}</svg><span>Предпросмотр камеры</span></div><div className="modal-actions"><button className="button secondary" onClick={()=>setCameras(v=>v.map(c=>c.id===selected.id?{...c,zone_points:[]}:c))}>Очистить</button><button className="button dark" onClick={saveZone} disabled={busy||(selected.zone_points?.length||0)<3}>Сохранить зону</button></div></div></div>}</>
}

function Summary({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function PanelTitle({eyebrow,title,vision=false}:{eyebrow:string;title:string;vision?:boolean}){return <div className="panel-title"><div><span className={vision?"eyebrow vision":"eyebrow"}>{eyebrow}</span><h3>{title}</h3></div></div>}
function ModalHead({eyebrow,title,close}:{eyebrow:string;title:string;close:()=>void}){return <div className="modal-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" onClick={close}>×</button></div>}
function CourseForm({busy,submit}:{busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Новая программа</h3><label>Название<input name="title" required placeholder="Вводный инструктаж"/></label><label>Формат<select name="course_type" defaultValue="instruction"><option value="instruction">Инструктаж</option><option value="knowledge_check">Проверка знаний по БиОТ</option></select></label><label>Материал или описание<textarea name="description" rows={5} placeholder="Текст, порядок прохождения или ссылка"/></label><label>Проходной балл<input name="passing_score" type="number" min="1" max="100" defaultValue="80" required/></label><button className="button dark" disabled={busy}>Создать программу</button></form>}
function QuestionForm({courses,busy,submit}:{courses:LearningCourse[];busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Добавить вопрос</h3><label>Проверка знаний<select name="course_id" required><option value="">Выберите</option>{courses.filter(c=>c.course_type==="knowledge_check").map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Вопрос<textarea name="question" rows={2} required/></label>{[1,2,3].map(n=><label key={n}>Вариант {n}<input name={`option_${n}`} required/></label>)}<label>Правильный вариант<select name="correct_option" defaultValue="0"><option value="0">Вариант 1</option><option value="1">Вариант 2</option><option value="2">Вариант 3</option></select></label><button className="button dark" disabled={busy}>Добавить вопрос</button></form>}
function CameraForm({busy,submit}:{busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Добавить камеру</h3><label>Название<input name="name" required placeholder="Камера 01"/></label><label>Расположение<input name="location" required placeholder="Склад · въезд"/></label><label>Адрес потока<input name="stream_url" placeholder="RTSP/HTTPS — хранится закрыто"/></label><label>Состояние<select name="status" defaultValue="offline"><option value="online">Онлайн</option><option value="offline">Офлайн</option><option value="maintenance">Обслуживание</option></select></label><button className="button dark" disabled={busy}>Добавить камеру</button></form>}
function EventForm({cameras,busy,submit}:{cameras:VisionCamera[];busy:boolean;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="panel compact-form" onSubmit={submit}><h3>Зафиксировать событие</h3><label>Камера<select name="camera_id" required><option value="">Выберите</option>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Нарушение<select name="event_type" defaultValue="no_helmet">{Object.entries(eventLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Комментарий<textarea name="notes" rows={3} placeholder="Что произошло и что видно на записи"/></label><button className="button dark" disabled={busy}>Создать событие</button></form>}
function Empty({text}:{text:string}){return <div className="module-empty">{text}</div>}
