"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export const trainingOptions=[
 ["intro","Вводный инструктаж"],["workplace","Инструктаж на рабочем месте"],["electrical","Электробезопасность"],
 ["ptm","ПТМ"],["first_aid","Первая помощь"],["industrial_safety","Промышленная безопасность"]
] as const;
const fieldOptions=[["medical_exam","Медосмотр"],["briefing","Инструктаж"],["training","Обучение"],["ppe","СИЗ"]] as const;
export type JobProfile={id:string;title:string;required_fields:string[];required_training_codes:string[];custom_training_name?:string|null;custom_training_names?:string[]|null};

export function PositionsPanel({initial,organizationId,supabaseUrl,supabaseKey}:{initial:JobProfile[];organizationId:string;supabaseUrl:string;supabaseKey:string}){
 const [items,setItems]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editing,setEditing]=useState<JobProfile|null>(null),[customs,setCustoms]=useState<string[]>([""]);
 function start(item?:JobProfile){setEditing(item||null);setCustoms(item?.custom_training_names?.length?item.custom_training_names:item?.custom_training_name?[item.custom_training_name]:[""])}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const customNames=customs.map(x=>x.trim()).filter(Boolean),trainings=[...new Set(["intro",...f.getAll("training").map(String),...customNames.map(name=>`custom:${name}`)])];const payload={organization_id:organizationId,title:String(f.get("title")),required_fields:f.getAll("field").map(String),required_training_codes:trainings,custom_training_names:customNames,custom_training_name:customNames[0]||null};const db=createClient(supabaseUrl,supabaseKey);const r=editing?await db.from("job_profiles").update(payload).eq("id",editing.id).select().single():await db.from("job_profiles").insert(payload).select().single();setBusy(false);if(r.error)return setMessage(r.error.code==="23505"?"Такая должность уже существует.":r.error.message);setItems(v=>editing?v.map(item=>item.id===editing.id?r.data as JobProfile:item):[r.data as JobProfile,...v]);const wasEditing=Boolean(editing);setEditing(null);setCustoms([""]);el.reset();setMessage(wasEditing?"Карточка должности обновлена.":"Карточка должности создана.")}
 async function remove(id:string){if(!confirm("Удалить карточку должности? Сотрудники сохранят выбранные требования."))return;setBusy(true);const r=await createClient(supabaseUrl,supabaseKey).from("job_profiles").delete().eq("id",id).select("id").maybeSingle();setBusy(false);if(r.error)return setMessage(r.error.message);if(!r.data)return setMessage("Карточка не удалена: проверьте права доступа.");setItems(v=>v.filter(x=>x.id!==id))}
 return <><section className="page-heading compact"><div><span className="eyebrow">СПРАВОЧНИК ОРГАНИЗАЦИИ</span><h1>Должности</h1><p>Обязательные поля и несколько видов обучения можно менять в любое время.</p></div></section>{message&&<div className="inline-notice">{message}</div>}<section className="split-grid"><form className="panel compact-form" onSubmit={save} key={editing?.id||"new"}><h3>{editing?"Изменить должность":"Новая должность"}</h3><label>Название<input name="title" required defaultValue={editing?.title||""} placeholder="Электромонтёр"/></label><fieldset className="check-group"><legend>Обязательные поля</legend>{fieldOptions.map(([v,l])=><label key={v}><input type="checkbox" name="field" value={v} defaultChecked={editing?editing.required_fields.includes(v):true}/><span>{l}</span></label>)}</fieldset><fieldset className="check-group"><legend>Необходимое обучение</legend>{trainingOptions.map(([v,l])=><label key={v}><input type="checkbox" name="training" value={v} defaultChecked={v==="intro"||Boolean(editing?.required_training_codes.includes(v))} disabled={v==="intro"}/><span>{l}{v==="intro"?" · обязательно":""}</span></label>)}</fieldset><fieldset className="repeat-fields"><legend>Другие виды обучения</legend>{customs.map((value,index)=><div key={index}><input value={value} onChange={event=>setCustoms(current=>current.map((item,i)=>i===index?event.target.value:item))} placeholder="Например: работа на высоте"/><button type="button" onClick={()=>setCustoms(current=>current.length===1?[""]:current.filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" className="text-button inline" onClick={()=>setCustoms(current=>[...current,""])}>＋ Добавить вид обучения</button></fieldset><div className="modal-actions inline-actions">{editing&&<button type="button" className="button secondary" onClick={()=>start()}>Отмена</button>}<button className="button dark" disabled={busy}>{busy?"Сохранение…":editing?"Сохранить изменения":"Создать должность"}</button></div></form><section className="panel position-list"><div className="panel-title"><div><span className="eyebrow">КАРТОЧКИ</span><h3>{items.length} должностей</h3></div></div>{items.length?items.map(item=><article className="position-card" key={item.id}><div><strong>{item.title}</strong><small>{item.required_training_codes.map(code=>trainingOptions.find(x=>x[0]===code)?.[1]||code.replace(/^custom:/,"")).join(" · ")}</small></div><div className="module-actions"><button onClick={()=>start(item)}>Изменить</button><button className="danger-link bare" disabled={busy} onClick={()=>remove(item.id)}>Удалить</button></div></article>):<div className="module-empty">Создайте первую карточку должности</div>}</section></section></>
}
