"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export const trainingOptions=[
 ["intro","Вводный инструктаж"],["workplace","Инструктаж на рабочем месте"],["electrical","Электробезопасность"],
 ["ptm","ПТМ"],["first_aid","Первая помощь"],["industrial_safety","Промышленная безопасность"],["other","Другое"]
] as const;
const fieldOptions=[["medical_exam","Медосмотр"],["briefing","Инструктаж"],["training","Обучение"],["ppe","СИЗ"]] as const;
export type JobProfile={id:string;title:string;required_fields:string[];required_training_codes:string[];custom_training_name?:string|null};

export function PositionsPanel({initial,organizationId,supabaseUrl,supabaseKey}:{initial:JobProfile[];organizationId:string;supabaseUrl:string;supabaseKey:string}){
 const [items,setItems]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setBusy(true);setMessage("");const trainings=[...new Set(["intro",...f.getAll("training").map(String)])];const r=await createClient(supabaseUrl,supabaseKey).from("job_profiles").insert({organization_id:organizationId,title:String(f.get("title")),required_fields:f.getAll("field").map(String),required_training_codes:trainings,custom_training_name:trainings.includes("other")?String(f.get("custom")||"")||null:null}).select().single();setBusy(false);if(r.error)return setMessage(r.error.code==="23505"?"Такая должность уже существует.":r.error.message);setItems(v=>[r.data as JobProfile,...v]);el.reset();setMessage("Карточка должности создана.")}
 async function remove(id:string){if(!confirm("Удалить карточку должности? Сотрудники сохранят выбранные требования."))return;setBusy(true);const r=await createClient(supabaseUrl,supabaseKey).from("job_profiles").delete().eq("id",id);setBusy(false);if(r.error)return setMessage(r.error.message);setItems(v=>v.filter(x=>x.id!==id))}
 return <><section className="page-heading compact"><div><span className="eyebrow">СПРАВОЧНИК ОРГАНИЗАЦИИ</span><h1>Должности</h1><p>Один раз задайте обязательные поля и обучение — затем применяйте их к сотрудникам.</p></div></section>{message&&<div className="inline-notice">{message}</div>}<section className="split-grid"><form className="panel compact-form" onSubmit={create}><h3>Новая должность</h3><label>Название<input name="title" required placeholder="Электромонтёр"/></label><fieldset className="check-group"><legend>Обязательные поля</legend>{fieldOptions.map(([v,l])=><label key={v}><input type="checkbox" name="field" value={v} defaultChecked/><span>{l}</span></label>)}</fieldset><fieldset className="check-group"><legend>Необходимое обучение</legend>{trainingOptions.map(([v,l])=><label key={v}><input type="checkbox" name="training" value={v} defaultChecked={v==="intro"} disabled={v==="intro"}/><span>{l}{v==="intro"?" · обязательно":""}</span></label>)}</fieldset><label>Название другого обучения<input name="custom" placeholder="Например: работа на высоте"/></label><button className="button dark" disabled={busy}>Создать должность</button></form><section className="panel position-list"><div className="panel-title"><div><span className="eyebrow">КАРТОЧКИ</span><h3>{items.length} должностей</h3></div></div>{items.length?items.map(item=><article className="position-card" key={item.id}><div><strong>{item.title}</strong><small>{item.required_training_codes.map(code=>trainingOptions.find(x=>x[0]===code)?.[1]||item.custom_training_name||code).join(" · ")}</small></div><button className="danger-link bare" disabled={busy} onClick={()=>remove(item.id)}>Удалить</button></article>):<div className="module-empty">Создайте первую карточку должности</div>}</section></section></>
}
