"use client";

import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type TaskItem = { id:string; title:string; description?:string|null; priority:string; status:string; assignee_id?:string|null; due_date:string; created_at:string };
export type TeamMember = { user_id:string; role:string; created_at:string; full_name?:string|null };
export type AuditEvent = { id:string; actor_id?:string|null; action:string; entity_type:string; entity_id?:string|null; created_at:string; before_data?:Record<string,unknown>|null; after_data?:Record<string,unknown>|null };

const taskLabels: Record<string,string> = { open:"Новая", in_progress:"В работе", done:"Выполнена", verified:"Проверена" };
const roleLabels: Record<string,string> = { owner:"Владелец", hse:"HSE", manager:"Руководитель", hr:"HR", member:"Наблюдатель" };
const auditLabels: Record<string,string> = { created:"Создано", updated:"Изменено", archived:"Архивировано", restored:"Восстановлено", deleted:"Удалено", approved:"Подтверждено", rejected:"Отклонено" };

export function TasksPanel({ initial, members, organizationId, supabaseUrl, supabaseKey }: { initial:TaskItem[]; members:TeamMember[]; organizationId:string; supabaseUrl:string; supabaseKey:string }) {
  const [tasks,setTasks]=useState(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function createTask(event:FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement=event.currentTarget; setBusy(true); setMessage("");
    const form=new FormData(formElement); const payload={ organization_id:organizationId, title:String(form.get("title")), description:String(form.get("description")||""), priority:String(form.get("priority")), due_date:String(form.get("due_date")), assignee_id:String(form.get("assignee_id")||"")||null };
    const result=await createClient(supabaseUrl,supabaseKey).from("tasks").insert(payload).select().single(); setBusy(false);
    if(result.error) return setMessage(result.error.message); setTasks(items=>[result.data as TaskItem,...items]); formElement.reset();
  }
  async function changeStatus(id:string,status:string) {
    setBusy(true); const patch:Record<string,unknown>={status}; if(status==="done") patch.completed_at=new Date().toISOString(); if(status==="verified") patch.verified_at=new Date().toISOString();
    const result=await createClient(supabaseUrl,supabaseKey).from("tasks").update(patch).eq("id",id).select().single(); setBusy(false);
    if(result.error) return setMessage(result.error.message); setTasks(items=>items.map(item=>item.id===id?result.data as TaskItem:item));
  }
  return <><section className="page-heading compact"><div><span className="eyebrow">КОРРЕКТИРУЮЩИЕ ДЕЙСТВИЯ</span><h1>Задачи</h1><p>Проблема должна получить ответственного, срок и доказательство закрытия.</p></div></section>{message&&<div className="inline-notice">{message}</div>}<section className="split-grid"><form className="panel compact-form" onSubmit={createTask}><h3>Новая задача</h3><label>Что нужно сделать<input name="title" required /></label><label>Описание<textarea name="description" rows={3}/></label><div className="form-grid"><label>Приоритет<select name="priority" defaultValue="medium"><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option><option value="critical">Критический</option></select></label><label>Срок<input name="due_date" type="date" required /></label></div><label>Ответственный<select name="assignee_id"><option value="">Не назначен</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.user_id.slice(0,8)} · {roleLabels[m.role]||m.role}</option>)}</select></label><button className="button dark" disabled={busy}>{busy?"Сохранение…":"Создать задачу"}</button></form><section className="panel task-list"><div className="panel-title"><div><span className="eyebrow">РАБОЧАЯ ОЧЕРЕДЬ</span><h3>{tasks.filter(x=>x.status!=="verified").length} активных</h3></div></div>{tasks.length?tasks.map(task=><article className="task-card" key={task.id}><div><span className={`status ${task.priority==="critical"?"red":task.priority==="high"?"yellow":"green"}`}>{taskLabels[task.status]||task.status}</span><strong>{task.title}</strong><small>{task.description||"Без описания"}</small></div><time>{new Intl.DateTimeFormat("ru-RU").format(new Date(`${task.due_date}T00:00:00`))}</time><select value={task.status} disabled={busy} onChange={e=>changeStatus(task.id,e.target.value)}><option value="open">Новая</option><option value="in_progress">В работе</option><option value="done">Выполнена</option><option value="verified">Проверена</option></select></article>):<div className="empty"><strong>Задач пока нет</strong><span>Создайте первое корректирующее действие.</span></div>}</section></section></>;
}

export function TeamPanel({ initial, organizationId, canAdmin }: { initial:TeamMember[]; organizationId:string; canAdmin:boolean }) {
  const [members,setMembers]=useState(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function invite(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement=event.currentTarget; setBusy(true); setMessage(""); const form=new FormData(formElement); const response=await fetch("/api/team",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,email:form.get("email"),role:form.get("role")})}); const body=await response.json(); setBusy(false); if(!response.ok)return setMessage(body.error); setMessage(body.invited?"Приглашение отправлено.":"Пользователь добавлен. Обновите страницу, чтобы увидеть его в списке."); formElement.reset(); }
  async function role(userId:string,role:string) { setBusy(true); const response=await fetch("/api/team",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,userId,role})}); const body=await response.json(); setBusy(false); if(!response.ok)return setMessage(body.error); setMembers(items=>items.map(item=>item.user_id===userId?{...item,role}:item)); }
  async function remove(userId:string) { if(!confirm("Удалить доступ пользователя к организации?"))return; setBusy(true); const response=await fetch(`/api/team?organizationId=${encodeURIComponent(organizationId)}&userId=${encodeURIComponent(userId)}`,{method:"DELETE"}); const body=await response.json(); setBusy(false); if(!response.ok)return setMessage(body.error); setMembers(items=>items.filter(item=>item.user_id!==userId)); }
  return <><section className="page-heading compact"><div><span className="eyebrow">ДОСТУП И РОЛИ</span><h1>Команда</h1><p>Каждый участник получает только необходимый уровень доступа.</p></div></section>{message&&<div className="inline-notice">{message}</div>}{canAdmin&&<form className="panel invite-form" onSubmit={invite}><label>Рабочая почта<input name="email" type="email" required placeholder="name@company.kz"/></label><label>Роль<select name="role" defaultValue="member">{Object.entries(roleLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="button dark" disabled={busy}>{busy?"Отправка…":"Пригласить"}</button></form>}<section className="panel table-panel"><table><thead><tr><th>Пользователь</th><th>Роль</th><th>Добавлен</th><th></th></tr></thead><tbody>{members.map(member=><tr key={member.user_id}><td><strong>{member.full_name||member.user_id.slice(0,12)}</strong><small className="sub-id">{member.user_id.slice(0,8)}</small></td><td>{canAdmin?<select value={member.role} disabled={busy} onChange={e=>role(member.user_id,e.target.value)}>{Object.entries(roleLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:roleLabels[member.role]||member.role}</td><td>{new Intl.DateTimeFormat("ru-RU").format(new Date(member.created_at))}</td><td>{canAdmin&&<button className="danger-link bare" onClick={()=>remove(member.user_id)}>Удалить доступ</button>}</td></tr>)}</tbody></table></section></>;
}

export function AuditPanel({ events, members }: { events:AuditEvent[]; members:TeamMember[] }) {
  const names=new Map(members.map(m=>[m.user_id,m.full_name||m.user_id.slice(0,8)]));
  return <><section className="page-heading compact"><div><span className="eyebrow">НЕИЗМЕНЯЕМАЯ ИСТОРИЯ</span><h1>Журнал действий</h1><p>Кто, когда и что изменил в системе.</p></div></section><section className="panel table-panel"><table><thead><tr><th>Действие</th><th>Объект</th><th>Пользователь</th><th>Дата и время</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td><span className="status green">{auditLabels[event.action]||event.action}</span></td><td><strong>{event.entity_type}</strong><small className="sub-id">{event.entity_id?.slice(0,8)||"—"}</small></td><td>{event.actor_id?names.get(event.actor_id)||event.actor_id.slice(0,8):"Система"}</td><td>{new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.created_at))}</td></tr>)}</tbody></table>{!events.length&&<div className="empty"><strong>Журнал пока пуст</strong><span>Новые изменения будут фиксироваться автоматически.</span></div>}</section></>;
}
