"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Target={id:string;label:string;chat_id:string;enabled:boolean};

export function VisionNotifications({organizationId,supabaseUrl,supabaseKey}:{organizationId:string;supabaseUrl:string;supabaseKey:string}){
 const [enabled,setEnabled]=useState(true),[targets,setTargets]=useState<Target[]>([]),[message,setMessage]=useState(""),[available,setAvailable]=useState(true),[busy,setBusy]=useState(false);
 const db=()=>createClient(supabaseUrl,supabaseKey);
 useEffect(()=>{let current=true;async function load(){const client=createClient(supabaseUrl,supabaseKey),[settings,list]=await Promise.all([client.from("vision_notification_settings").select("enabled").eq("organization_id",organizationId).maybeSingle(),client.from("vision_notification_targets").select("id,label,chat_id,enabled").eq("organization_id",organizationId).order("created_at")]);if(!current)return;if(settings.error||list.error){setAvailable(false);return}setEnabled(settings.data?.enabled!==false);setTargets((list.data||[]) as Target[])}void load();return()=>{current=false}},[organizationId,supabaseKey,supabaseUrl]);
 async function toggle(){setBusy(true);const next=!enabled,result=await db().from("vision_notification_settings").upsert({organization_id:organizationId,enabled:next},{onConflict:"organization_id"});setBusy(false);if(result.error)return setMessage(result.error.message);setEnabled(next);setMessage(next?"Telegram-уведомления включены.":"Telegram-уведомления выключены.")}
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);const result=await db().from("vision_notification_targets").insert({organization_id:organizationId,label:String(data.get("label")||"Получатель"),chat_id:String(data.get("chat_id")||"").trim()}).select("id,label,chat_id,enabled").single();setBusy(false);if(result.error)return setMessage(result.error.message);setTargets(value=>[...value,result.data as Target]);form.reset();setMessage("Получатель добавлен.")}
 async function remove(id:string){setBusy(true);const result=await db().from("vision_notification_targets").delete().eq("id",id);setBusy(false);if(result.error)return setMessage(result.error.message);setTargets(value=>value.filter(item=>item.id!==id))}
 async function test(id:string){setBusy(true);const response=await fetch("/api/vision/telegram/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,targetId:id})}),result=await response.json();setBusy(false);setMessage(response.ok?"Тестовое сообщение отправлено в Telegram.":result.error||"Ошибка отправки.")}
 return <section className="panel telegram-panel"><div className="panel-title"><div><span className="eyebrow vision">МГНОВЕННЫЕ УВЕДОМЛЕНИЯ</span><h3>Единый Telegram-бот</h3><p className="muted">Один бот обслуживает всех клиентов. Получатели и объекты разделены по организациям.</p></div><button className={`notification-switch ${enabled?"enabled":""}`} disabled={busy||!available} onClick={toggle}>{enabled?"Включены":"Выключены"}</button></div>{available?<><form className="telegram-form" onSubmit={add}><label>Получатель или группа<input name="label" placeholder="Смена А / Начальник участка" required/></label><label>Telegram Chat ID<input name="chat_id" placeholder="Например, -1001234567890" required/></label><button className="button dark" disabled={busy}>Добавить</button></form><div className="telegram-targets">{targets.length?targets.map(target=><article key={target.id}><span>✈</span><div><strong>{target.label}</strong><small>{target.chat_id}</small></div><button disabled={busy} onClick={()=>test(target.id)}>Тест</button><button className="danger-link" disabled={busy} onClick={()=>remove(target.id)}>Удалить</button></article>):<p className="muted">Добавьте личный чат или рабочую Telegram-группу. Отдельный бот каждому пользователю не нужен.</p>}</div></>:<div className="integration-pending">Схема Safety Vision Cloud подготовлена. После применения миграции здесь появятся маршруты Telegram и Edge Agent.</div>}{message&&<div className="inline-notice">{message}</div>}</section>
}
